# Do not edit this script directly, edit create-tests.bash
# Generated by Michael Gregg
# 3-15-2011
. ./testenv.sh

run_cns_tests()
{

rlPhaseStartTest "ipa-i18n-3: Changing lastname of $uname1 to Oskar"
    rlRun "ipa user-mod --last='Oskar' $uname1" 0 "Modifying lastname of $uname1 to Oskar"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-4: checking to ensuer that the lastname of $uname1 is Oskar"
        rlRun "ipa user-find --all $uname1 | grep 'Oskar'" 0 "Checking to ensure that the lastname of $uname1 is Oskar"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-5: Changing lastname of $uname1 to Anders"
    rlRun "ipa user-mod --last='Anders' $uname1" 0 "Modifying lastname of $uname1 to Anders"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-6: checking to ensuer that the lastname of $uname1 is Anders"
        rlRun "ipa user-find --all $uname1 | grep 'Anders'" 0 "Checking to ensure that the lastname of $uname1 is Anders"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-7: Changing lastname of $uname1 to Örjan"
    rlRun "ipa user-mod --last='Örjan' $uname1" 0 "Modifying lastname of $uname1 to Örjan"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-8: checking to ensuer that the lastname of $uname1 is Örjan"
        rlRun "ipa user-find --all $uname1 | grep 'Örjan'" 0 "Checking to ensure that the lastname of $uname1 is Örjan"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-9: Changing lastname of $uname1 to Jonas"
    rlRun "ipa user-mod --last='Jonas' $uname1" 0 "Modifying lastname of $uname1 to Jonas"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-10: checking to ensuer that the lastname of $uname1 is Jonas"
        rlRun "ipa user-find --all $uname1 | grep 'Jonas'" 0 "Checking to ensure that the lastname of $uname1 is Jonas"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-11: Changing lastname of $uname1 to Ulf"
    rlRun "ipa user-mod --last='Ulf' $uname1" 0 "Modifying lastname of $uname1 to Ulf"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-12: checking to ensuer that the lastname of $uname1 is Ulf"
        rlRun "ipa user-find --all $uname1 | grep 'Ulf'" 0 "Checking to ensure that the lastname of $uname1 is Ulf"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-13: Changing lastname of $uname1 to Äke"
    rlRun "ipa user-mod --last='Äke' $uname1" 0 "Modifying lastname of $uname1 to Äke"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-14: checking to ensuer that the lastname of $uname1 is Äke"
        rlRun "ipa user-find --all $uname1 | grep 'Äke'" 0 "Checking to ensure that the lastname of $uname1 is Äke"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-15: Changing lastname of $uname1 to Bertold"
    rlRun "ipa user-mod --last='Bertold' $uname1" 0 "Modifying lastname of $uname1 to Bertold"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-16: checking to ensuer that the lastname of $uname1 is Bertold"
        rlRun "ipa user-find --all $uname1 | grep 'Bertold'" 0 "Checking to ensure that the lastname of $uname1 is Bertold"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-17: Changing lastname of $uname1 to Bruno"
    rlRun "ipa user-mod --last='Bruno' $uname1" 0 "Modifying lastname of $uname1 to Bruno"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-18: checking to ensuer that the lastname of $uname1 is Bruno"
        rlRun "ipa user-find --all $uname1 | grep 'Bruno'" 0 "Checking to ensure that the lastname of $uname1 is Bruno"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-19: Changing lastname of $uname1 to Didier"
    rlRun "ipa user-mod --last='Didier' $uname1" 0 "Modifying lastname of $uname1 to Didier"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-20: checking to ensuer that the lastname of $uname1 is Didier"
        rlRun "ipa user-find --all $uname1 | grep 'Didier'" 0 "Checking to ensure that the lastname of $uname1 is Didier"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-21: Changing lastname of $uname1 to Éric"
    rlRun "ipa user-mod --last='Éric' $uname1" 0 "Modifying lastname of $uname1 to Éric"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-22: checking to ensuer that the lastname of $uname1 is Éric"
        rlRun "ipa user-find --all $uname1 | grep 'Éric'" 0 "Checking to ensure that the lastname of $uname1 is Éric"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-23: Changing lastname of $uname1 to Jean-Luc"
    rlRun "ipa user-mod --last='Jean-Luc' $uname1" 0 "Modifying lastname of $uname1 to Jean-Luc"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-24: checking to ensuer that the lastname of $uname1 is Jean-Luc"
        rlRun "ipa user-find --all $uname1 | grep 'Jean-Luc'" 0 "Checking to ensure that the lastname of $uname1 is Jean-Luc"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-25: Changing lastname of $uname1 to Laurent"
    rlRun "ipa user-mod --last='Laurent' $uname1" 0 "Modifying lastname of $uname1 to Laurent"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-26: checking to ensuer that the lastname of $uname1 is Laurent"
        rlRun "ipa user-find --all $uname1 | grep 'Laurent'" 0 "Checking to ensure that the lastname of $uname1 is Laurent"
rlPhaseEnd


rlPhaseStartTest "ipa-i18n-27: Changing lastname of $uname1 to Têko"
    rlRun "ipa user-mod --last='Têko' $uname1" 0 "Modifying lastname of $uname1 to Têko"
rlPhaseEnd

rlPhaseStartTest "ipa-i18n-28: checking to ensuer that the lastname of $uname1 is Têko"
        rlRun "ipa user-find --all $uname1 | grep 'Têko'" 0 "Checking to ensure that the lastname of $uname1 is Têko"
rlPhaseEnd



}

