# This scrip will generate the tests scrip that utilized the entries in 
#  firstnames.txt
# A new scrip will be created called firstname-tests.sh
# Do not edit firstname-tests.sh directly, instead, edit the templates here, 
# and re-run this script. 
# This script assumes that this is the first set of testcases called after the 
# creation of the users in runtest.sh, so the first test case number will be 3. 
# Incrimenting from there
# Michael Gregg 3-15-2011

export num=3
export bnum=4

# Headder:
echo '# Do not edit this script directly, edit create-firstname-tests.bash
# Generated by Michael Gregg
# 3-15-2011
. ./testenv.sh' > firstname-tests.sh

# adding a null line
echo "" >> firstname-tests.sh

echo 'run_firstname_tests()
{' >> firstname-tests.sh

echo "" >> firstname-tests.sh

cat firstnames.list | while read char; do 
	echo $char
	# Replace vars in template
	cat template1 | sed s/%char/$char/g | sed s/'%bnum'/$bnum/g | sed s/'%num'/$num/g >> firstname-tests.sh
	echo "" >> firstname-tests.sh
	# Incriment num and bnum
	let num=$num+2
	let bnum=$bnum+2
done

echo "" >> firstname-tests.sh
# Finish firstname section
echo '}' >> firstname-tests.sh

echo "" >> firstname-tests.sh

