# This scrip will generate the tests scrip that utilized the entries in 
#  firstnames.list, cns.list, and rejection.list
# A new scrip will be created called firstname-tests.sh, cns-tests.sh, and
# rejection-tests.sh
# Do not edit these scripts directly, instead, edit the templates here, 
# and re-run this script. 
# This script assumes that this is the first set of testcases called after the 
# creation of the users in runtest.sh, so the first test case number will be 3. 
# Incrimenting from there
# Michael Gregg 3-15-2011

export num=3
export bnum=4
numfile=`mktemp`
bnumfile=`mktemp`

echo '# Do not edit this script directly, edit create-tests.bash
# Generated by Michael Gregg
# 3-15-2011
. ./testenv.sh' > firstname-tests.sh
cat ./firstname-tests.sh > ./cns-tests.sh
cat ./firstname-tests.sh > ./rejection-tests.sh

#########################################################################
# CNS
#########################################################################

# adding a null line
echo "" >> cns-tests.sh

echo 'run_cns_tests()
{' >> cns-tests.sh

echo "" >> cns-tests.sh

cat cns.list | while read char; do 
	echo $char
	# Replace vars in template
	cat template1 | sed s/%char/$char/g | sed s/'%bnum'/$bnum/g | sed s/'%num'/$num/g >> cns-tests.sh
	echo "" >> cns-tests.sh
	# Incriment num and bnum
	let num=$num+2
	let bnum=$bnum+2
	echo $num > $numfile
	echo $bnum > $bnumfile
done

echo "" >> cns-tests.sh
# Finish cns section
echo '}' >> cns-tests.sh

echo "" >> cns-tests.sh

#########################################################################
# Rejection
#########################################################################

# adding a null line
echo "" >> rejection-tests.sh

echo 'run_rejection_tests()
{' >> rejection-tests.sh

echo "" >> rejection-tests.sh

# Repopulate num and bnum
num=`cat $numfile`
bnum=`cat $bnumfile`

cat rejection.list | while read char; do 
	echo $char
	# Replace vars in template
	cat template2 | sed s/%char/$char/g | sed s/'%bnum'/$bnum/g | sed s/'%num'/$num/g >> rejection-tests.sh
	echo "" >> rejection-tests.sh
	# Incriment num and bnum
	let num=$num+2
	let bnum=$bnum+2
	echo $num > $numfile
	echo $bnum > $bnumfile
done

echo "" >> rejection-tests.sh
# Finish rejection section
echo '}' >> rejection-tests.sh

echo "" >> rejection-tests.sh


#########################################################################
# Firstname test script generation
#########################################################################

# adding a null line
echo "" >> firstname-tests.sh

echo 'run_firstname_tests()
{' >> firstname-tests.sh

echo "" >> firstname-tests.sh

# Repopulate num and bnum
num=`cat $numfile`
bnum=`cat $bnumfile`

cat firstnames.list | while read char; do 
	echo $char
	# Replace vars in template
	cat template3 | sed s/%char/$char/g | sed s/'%bnum'/$bnum/g | sed s/'%num'/$num/g >> firstname-tests.sh
	echo "" >> firstname-tests.sh
	# Incriment num and bnum
	let num=$num+2
	let bnum=$bnum+2
	echo $num > $numfile
	echo $bnum > $bnumfile
done

echo "" >> firstname-tests.sh
# Finish firstname section
echo '}' >> firstname-tests.sh

echo "" >> firstname-tests.sh

