ADMINID=admin
ADMINPW=Secret123
ROOTDN="cn=Directory Manager"
ROOTDNPWD=Secret123
DNSFORWARD=10.14.63.12
RELM=testrelm
DOMAIN=testdomain
NTPSERVER=clock.redhat.com

export ADMINID ADMINPW ROOTDN ROOTDNPWD DNSFORWARD RELM DOMAIN NTPSERVER
