ADMINID=admin
ADMINPW=Secret123
ROOTDN="cn=Directory Manager"
ROOTDNPWD=Secret123
DNSFORWARD=10.14.63.12
RELM=TESTRELM.COM
DOMAIN=testrelm.com
NISDOMAIN=ipatest
NTPSERVER=clock.redhat.com

export ADMINID ADMINPW ROOTDN ROOTDNPWD DNSFORWARD RELM DOMAIN NTPSERVER
