ADMINID=admin
ADMINPW=Secret123
ROOTDN="cn=Directory Manager"
ROOTDNPWD=Secret123
DNSFORWARD=10.14.63.12
RELM=TESTRELM.COM
DOMAIN=testrelm.com
BASEDN="dc=testrelm,dc=com"
NISDOMAIN=ipatest
NTPSERVER=10.16.255.1

export ADMINID ADMINPW ROOTDN ROOTDNPWD DNSFORWARD RELM DOMAIN NTPSERVER
