#!/bin/bash

export PATH=./x86_64/:$PATH:
export LD_LIBRARY_PATH=./x86_64/:$LD_LIBRARY_PATH:

PREFIX=hammertest
ROUNDS=1000
COUNT=500
DEPTH=10
REALM=DSQA.SJC2.REDHAT.COM


CCACHE=`mktemp /tmp/krb5cc_XXXXXX`
kdc5_hammer -p $PREFIX -n $COUNT -D $DEPTH -R $ROUNDS -r $REALM -p $PREFIX -t -c FILE:$CCACHE
rm -f $CCACHE

