#!/bin/bash
# by yzhang
# copy repo file to desired location 

copyrepo()
{
	remote_server=$1
	server=$2
	uri=$3
	file=$4
	echo "copy repo starts..."
	if [ -z $remote_server ]
	then
		echo "	no server defined, exit"
		return
	fi
	if [ -z $server ] || [ -z $uri ] || [ -z $file ]
	then
		echo "	no repo defined, exit"
		return
	fi
	repourl="http://$server/$uri/$file"
	echo "	remote server=[$remote_server"
	echo "	resource from=[http://$server/$uri/$file]"
	log=/tmp/copyrepo.$RANDOM.log
	ssh root@${remote_server} "cd /etc/yum.repos.d/;mv -f $file $file.last 2>&1 1>/dev/null; wget $repourl 2>&1 1>/dev/null " > $log
	if grep "Saving to" $log 2>&1 1>/dev/null
	then
		echo "	success"
		grep "	Saving to" $log
	else
		echo "	failed"
		cat $log
	fi
	rm $log
	echo "copy repo finished"
}

yuminstall()
{
	remote_server=$1
	pkg=$2
	echo "yum install ipa starts..."
	if [ -z $remote_server ]
	then
		echo "	no remote server defined, do nothing"
		return
	fi
	echo "	remote server=[$remote_server]"
	echo "	package want to install=[$pkg]"
	log=/tmp/yuminstallipa.$RANDOM.log
	ssh root@${remote_server} "yum search $pkg 2>&1 1>/dev/null" > $log
	if grep "No [m|M]atches found" $log 2>&1 1>/dev/null
	then
		echo "	failed"
		echo "	check your repo file"
		cat $log
	else
		echo "	repo is ready"
	fi
	ssh root@${remote_server} "rpm -qa | grep $pkg" > $log
	if grep "$pkg" $log 2>&1 1>/dev/null
	then
		echo "found [$pkg] on [$remote_server], can not continue"
		cat $log
		return
	else
		echo "ready to do yum install"
		ssh root@${remote_server} "yes yes | yum install $pkg"
	fi
	rm $log
	echo "yum install ipa finished"
}

ipaserversetup()
{
# ipa-server-install -N -U --hostname=mv32a-vm.idm.lab.bos.redhat.com -r IDM.LAB.BOS.REDHAT.COM -p redhat123 -P redhat123 -a redhat123 -u root
	remote_server=$1
	echo "install ipa starts..."
	if [ -z $remote_server ]
	then
		echo "	no remote server defined, do nothing"
		return
	fi
	ssh root@${remote_server} "ipa-server-install -N -U --hostname=mv32a-vm.idm.lab.bos.redhat.com -r IDM.LAB.BOS.REDHAT.COM -p redhat123 -P redhat123 -a redhat123 -u root"

}

remote_server="mv32a-vm.idm.lab.bos.redhat.com"
repo_server="mv64j-vm.idm.lab.bos.redhat.com"
repo_uri="/repo/"
repo_file="ipav2-32.repo"

#copyrepo $remote_server $repo_server $repo_uri $repo_file
#yuminstall $remote_server "ipa-server"
#ipaserversetup $remote_server

