#! /bin/sh
. ./vmconf
. ./functions

#vmup mv32a ds81installed
#vmpoweron mv32a
vmsave_as mv32a test just.test

# Available functions
# [vmup]
#	usage  : vmup <vmlabel> <available environment>
#	example: vmup mv64a ds81rpm
#	  -- bring up one vm host (identified by vmlabel) to certain environment
#
# [vmupdate]
#	usage  : vmupdate <vmlabel> <targetted environment>
#	example: vmupdate mv32a ds81imstalled
# 	  -- save current image, identified by vmlabel, as targetted environment
#
# [vmpoweron]
#	usage  : vmpoweron <vmlabel>
#	example: vmpoweron mv32d
#	  -- just turn on one vm, identified by vmlabel
#
# [vmpoweroff]
#	usage  : vmpoweroff <vmlabel>
#	example: vmpoweroff mv32d
#	  -- just turn off one vm, identified by vmlabel
#
# [vmsave_as]
#	usage  : vmsave_as <vmlabel> <vm alias> <vm file name>
#	example: vmsave-as mv32a ipa20rpm ds.rpm
#	  -- save current image, identified by vmlabel, 
#			with real file name, rhel5-i386-mv32a-vm.img.ds.rpm.2009-04-14, 
#			notice : suffix "rhel5-i386-mv32a-vm.img" and date is automatic added
#			and create a link "ipa20rpm" to it

# Syntax : vmup <vmlabel> <env target>
#################################################################
#          Available VM resources                               #
#  +=========================================================+  #
#  | vmlabel	  OS         |  possible environment target  |  #
#  +---------------------------------------------------------+  #
#  |  mv32a   RHEL 5 i386    | qa, ds81rpm, ds81installed    |  #
#  |  mv32b          " "     | qa                            |  #
#  |  mv32c          " "     | qa                            |  #
#  |  mv32d   RHEL 4 i386    | qa, ds81rpm, ds81installed    |  #
#  |  mv32e          " "     | qa                            |  #
#  |  mv32f   Window XP      | qa, ds81console               |  #
#  |  mv32g   Window 2003    | qa                            |  #
#  |  mv32h                  |                               |  #
#  |  mv32i                  |                               |  #
#  |  mv32j                  |                               |  #
#  |  -----------------------------------------------------  |  #
#  |  mv64a   RHEL 5 x86_64  | qa, ds81rpm, ds81installed    |  #
#  |  mv64b          " "     | qa, ds81rpm, ds81installed    |  #
#  |  mv64c          " "     | qa                            |  #
#  |  mv64d   RHEL 4 x86_64  | qa, ds81rpm,                  |  #
#  |  mv64e          " "     | qa                            |  #
#  |  mv64f                  |                               |  #
#  |  mv64g                  |                               |  #
#  |  mv64h   RHEL 5 x86_64  |                               |  #
#  |  mv64i                  |                               |  #
#  |  mv64j   Fedora 10 [test kickoff machine]               |  #
#  +=========================================================+  #
#################################################################


