#! /bin/sh
. ./vmconf
. ./functions
. ./remotecontrol

#vmsave_as mv64b sasl ds81.sasl 
#vmsave_as mv64c sasl ds81.sasl 
#vmsave_as mv32c sasl ds81.sasl 

onebyone(){
	env=$1
	if [ -z $env ];then
		echo "env lable?"
		exit
	fi
	vmup mv64b $env
	vmup mv64c $env
	vmup mv32c $env
}

allatonce(){
	env=$1
	if [ -z $env ];then
		echo "env lable?"
		exit
	fi
  {
	vmup mv64b $env
  }&
  {
	vmup mv64c $env
  }&
  {
	vmup mv32c $env
  }&
}

#allatonce ds81
#vmup mv64a qa

vmsave_as mv64a ipa2
#vmsave_as mv32a ds90
#vmup mv64a qa
#vmupdate mv32b qa
#vmupdate mv32c qa
#vmupdate mv64a qa
#vmupdate mv64b qa
#vmupdate mv64c qa

#vmup mv64c qa
#vmup mv32a ds81installed
#vmup mv32b qa



#vmupdate mv32a qa
#vmupdate mv32a ipav2installed
#vmupdate mv32b  qa


#vmpoweron mv32a


# Available functions
# [vmup]
#	usage  : vmup <vmlabel> <available environment>
#	example: vmup mv64a ds81rpm
#	  -- shutdown current image, bring up one vm host (identified by vmlabel) to certain environment
#
# [vmupdate]
#	usage  : vmupdate <vmlabel> <targetted environment>
#	example: vmupdate mv32a ds81imstalled
# 	  -- save current image, identified by vmlabel, as targetted environment
#
# [vmpoweron]
#	usage  : vmpoweron <vmlabel>
#	example: vmpoweron mv32d
#	  -- just turn on one vm, identified by vmlabel
#
# [vmpoweroff]
#	usage  : vmpoweroff <vmlabel>
#	example: vmpoweroff mv32d
#	  -- just turn off one vm, identified by vmlabel
#
# [vmsave_as]
#	usage  : vmsave_as <vmlabel> <vm alias> 
#	example: vmsave-as mv32a ipa20rpm ds.rpm
#	  -- save current image, identified by vmlabel, 
#			with real file name, rhel5-i386-mv32a-vm.img.ds.rpm.2009-04-14, 
#			notice : prefix "rhel5-i386-mv32a-vm.img" and suffix date are automatic added
#			and create a link "ipa20rpm" to it

# Syntax : vmup <vmlabel> <env target>
#################################################################
#          Available VM resources                               #
#  +=========================================================+  #
#  | vmlabel	  OS         |  possible environment target  |  #
#  +---------------------------------------------------------+  #
#  |  mv32a   RHEL 5 i386    | qa, ds81rpm, ds81installed    |  #
#  |                         | qa, ipav2rpm, ipav2installed  |  #
#  |  mv32b          " "     | qa                            |  #
#  |  mv32c          " "     | qa                            |  #
#  |  mv32d   RHEL 4 i386    | qa, ds81rpm, ds81installed    |  #
#  |  mv32e          " "     | qa                            |  #
#  |  mv32f   Window XP      | qa, ds81console               |  #
#  |  mv32g   Window 2003    | qa                            |  #
#  |  mv32h                  |                               |  #
#  |  mv32i                  |                               |  #
#  |  mv32j                  | startpoint ipacode            |  #
#  |  -----------------------------------------------------  |  #
#  |  mv64a   RHEL 5 x86_64  | qa, ds81rpm, ds81installed    |  #
#  |  mv64b          " "     | qa, ds81rpm, ds81installed    |  #
#  |                 " "     |     ipav2rpm,                 |  #
#  |  mv64c          " "     | qa                            |  #
#  |  mv64d   RHEL 4 x86_64  | qa, ds81rpm,                  |  #
#  |  mv64e          " "     | qa                            |  #
#  |  mv64f                  |                               |  #
#  |  mv64g                  |                               |  #
#  |  mv64h   RHEL 5 x86_64  |                               |  #
#  |  mv64i                  |                               |  #
#  |  mv64j   Fedora 10 [test kickoff machine]               |  #
#  +=========================================================+  #
#################################################################


