#!/bin/sh

#############################
#     Global variables      #
############################# 
DOMAIN=idm.lab.bos.redhat.com
VMHOSTER32=giant.$DOMAIN
VMHOSTER64=goliath.$DOMAIN
IMAGE_BASE=/export/images
IMAGE_BK_BASE=$IMAGE_BASE/vms
resource_server="mv64j-vm.idm.lab.bos.redhat.com"

# there is only one function in this file: setupvm
setupvm(){

vmlabel=$1
if [ -z $vmlabel ];then
	echo "[ERROR] vmlabel is not given, exit"
	exit
fi
hostname="${vmlabel}-vm.$DOMAIN"
case $vmlabel in
	mv32[abc])
		hoster=$VMHOSTER32
		imagename="rhel5-i386-${vmlabel}-vm"
		imagefile=$IMAGE_BASE/rhel5-i386-${vmlabel}-vm.img
		imagebase=$IMAGE_BK_BASE/rhel5-i386/${vmlabel}-vm
		repo_ipa="http://$resource_server/repo/ipa32.repo"
		;;
	mv32[defg])
		hoster=$VMHOSTER32
		imagename="rhel4-i386-{$vmlabel}-vm"
		imagefile=$IMAGE_BASE/rhel4-i386-${vmlabel}-vm.img
		imagebase=$IMAGE_BK_BASE/rhel4-i386/${vmlabel}-vm
		;;
	mv32h)
		echo "	[$vmlabel] is not ready"
		;;
	mv32i)
		echo "	[$vmlabel] is not ready"
		;;
	mv32j)
		hoster=$VMHOSTER32
		imagename="Fedora-i386-${vmlabel}-vm"
		imagefile=$IMAGE_BASE/Fedora-i386-${vmlabel}-vm.img
		imagebase=$IMAGE_BK_BASE/fedora-i386/${vmlabel}-vm
		;;
	mv64[abc])
		hoster=$VMHOSTER64
		imagename="rhel5-x86_64-${vmlabel}-vm"
		imagefile=$IMAGE_BASE/rhel5-x86_64-${vmlabel}-vm.img
		imagebase=$IMAGE_BK_BASE/rhel5-x86_64/${vmlabel}-vm
		repo_ipa="http://$resource_server/repo/ipa64.repo"
		;;
	mv64[de])
		hoster=$VMHOSTER64
		imagename="rhel4-x86_64-mv64d-vm"
		imagefile=$IMAGE_BASE/rhel4-x86_64-${vmlabel}-vm.img
		imagebase=$IMAGE_BK_BASE/rhel4-x86_64/${vmlabel}-vm
		;;
	mv64f)
		echo "	[$vmlabel] is not ready"
		;;
	mv64g)
		echo "	[$vmlabel] is not ready"
		;;
	mv64h)
		echo "	[$vmlabel] is not ready"
		;;
	mv64i)
		echo "	[$vmlabel] is not ready"
		;;
	mv64j)
		echo "	[$vmlabel] this is reserved"
		;;
	*)
		echo "[ERROR] unknow enviroment [$vmlabel], exit program"
		exit
		;;
esac

}
