#!/bin/bash
# By  : Automatic Generated by at.3.testcase.pl
# Date: Wed Oct 19 14:47:04 2011

#############################################
#  test suite: selfservice BZs
#############################################

selfservice_bz()
{
	selfservice_bz_envsetup
	selfservice_bz_772106 # ipa selfservice-add --raw returns "internal error" message
	selfservice_bz_772675 # ipa selfservice-mod --raw returns "internal error" message
	selfservice_bz_747730 # ipa selfservice-mod "edit address" --permissions="" delete a selfservice permission
	selfservice_bz_747741 # ipa selfservice-mod : provide wrong attr for --attrs delete a selfservice permission
	selfservice_bz_747693 # ipa selfservice-find --raw returns "internal error"
	selfservice_bz_747720 # ipa selfservice-find --permission="" returns internal error
	selfservice_bz_747722 # ipa selfservice-find --attrs="" returns internal error
	selfservice_bz_cleanup
}

selfservice_bz_envsetup() 
{
	rlPhaseStartSetup "selfservice_bz_envsetup"
		#environment setup starts here
		#KinitAsAdmin
		#Kcleanup
		#environment setup ends   here
	rlPhaseEnd
} #envsetup

selfservice_bz_cleanup()
{
	rlPhaseStartCleanup "selfservice_bz_cleanup"
		#environment cleanup starts here
		#KinitAsAdmin
		#Kcleanup
		#environment cleanup ends   here
	rlPhaseEnd
} #envcleanup

######################################################################
# ipa selfservice-add --raw returns "internal error" message
######################################################################
selfservice_bz_772106()
{
	rlPhaseStartTest "ipa-selfservice-bugzilla-001: bz772106 ipa selfservice-add --raw returns internal error message"
                rlRun "rlDistroDiff keyctl"
		KinitAsAdmin
		local testID="selfservice_bz_772106"
		local tmpout=$TmpDir/selfservice_bz_772106.$RANDOM.out
		local attrs_TestValue="l"
		rlLog "BZ Test Running: ipa selfservice-add $testID --attrs=$attrs_TestValue --raw > $tmpout 2>&1"
		ipa selfservice-add $testID --attrs=$attrs_TestValue --raw > $tmpout 2>&1
		if [ $? -eq 0 ]; then
			rlPass "BZ 772106 not found"
		elif [ $(grep "ipa: ERROR: an internal error has occurred" $tmpout|wc -l) -eq 1 ]; then
			rlFail "BZ 772106 found...ipa selfservice-add --raw returns internal error message"
		fi
		# Post Test Cleanup:
		ipa selfservice-del $testID > /dev/null 2>&1
		[ -f $tmpout ] && rm $tmpout
		Kcleanup
	rlPhaseEnd
} #selfservice_bz_772106

######################################################################
# ipa selfservice-mod --raw returns "internal error" message
######################################################################
selfservice_bz_772675()
{
	rlPhaseStartTest "ipa-selfservice-bugzilla-002: bz772675 ipa selfservice-mod --raw returns internal error message"
                rlRun "rlDistroDiff keyctl"
		KinitAsAdmin
		local testID="selfservice_bz_772675"
		local tmpout=$TmpDir/selfservice_bz_772675.$RANDOM.out
		local attrs_TestValue="l"
		# Pre Test Setup:
		ipa selfservice-add $testID --attrs=l > /dev/null
		# BZ Test:
		rlLog "BZ Test Running: ipa selfservice-mod $testID --attrs=mobile --raw > $tmpout 2>&1"
		ipa selfservice-mod $testID --attrs=mobile --raw > $tmpout 2>&1
		if [ $? -eq 0 ]; then
			rlPass "BZ 772675 not found"
		elif [ $(grep "ipa: ERROR: an internal error has occurred" $tmpout|wc -l) -eq 1 ]; then
			rlFail "BZ 772675 found...ipa selfservice-mod --raw returns internal error message"
		fi
		# Post Test Cleanup:
		ipa selfservice-del $testID > /dev/null 2>&1
		[ -f $tmpout ] && rm $tmpout
		Kcleanup
	rlPhaseEnd
} #selfservice_bz_772675

######################################################################
# ipa selfservice-mod "edit address" --permissions="" delete a selfservice permission
######################################################################
selfservice_bz_747730()
{
	rlPhaseStartTest "ipa-selfservice-bugzilla-003: bz747730 ipa selfservice-mod edit address --permissions=\"\" delete a selfservice permission"
                rlRun "rlDistroDiff keyctl"
		KinitAsAdmin
		local testID="selfservice_bz_747730"
		local tmpout=$TmpDir/selfservice_bz_747730.$RANDOM.out
		local attrs_TestValue="l"
		# Pre Test Setup:
		ipa selfservice-add $testID --attrs=l > /dev/null
		# BZ Test:
		rlLog "BZ Test Running: ipa selfservice-mod $testID --permissions=\"\" > $tmpout 2>&1"
		ipa selfservice-mod $testID --permissions="" > /dev/null 2>&1
		if [ $? -eq 0 ]; then
			rlPass "BZ 747730 not found"
		elif [ $(ipa selfservice-show $testID 2>&1|grep "ipa: ERROR: ACI with name \"$testID\" not found" |wc -l) -eq 1 ]; then
			rlFail "BZ 747730 found...ipa selfservice-mod edit address --permissions=\"\" delete a selfservice permission"
		fi
		# Post Test Cleanup:
		ipa selfservice-del $testID > /dev/null 2>&1
		[ -f $tmpout ] && rm $tmpout
		Kcleanup
	rlPhaseEnd
} #selfservice_bz_747730

######################################################################
# ipa selfservice-mod : provide wrong attr for --attrs delete a selfservice permission
######################################################################
selfservice_bz_747741()
{
	rlPhaseStartTest "ipa-selfservice-bugzilla-004: bz747741 ipa selfservice-mod provide wrong attr for --attrs delete a selfservice permission"
                rlRun "rlDistroDiff keyctl"
		KinitAsAdmin
		local testID="selfservice_bz_747741"
		local tmpout=$TmpDir/selfservice_bz_747741.$RANDOM.out

		# Pre Test Setup:
		ipa selfservice-add $testID --attrs=l > /dev/null

		# BZ Test:
		rlLog "BZ Test Running: ipa selfservice-mod $testID --attrs=badattrs > $tmpout 2>&1"
		ipa selfservice-mod $testID --attrs=badattrs > /dev/null 2>&1
		if [ $? -eq 0 ]; then
			rlPass "BZ 747741 not found"
		elif [ $(ipa selfservice-show $testID 2>&1|grep "ipa: ERROR: ACI with name \"$testID\" not found" |wc -l) -eq 1 ]; then
			rlFail "BZ 747741 found...ipa selfservice-mod provide wrong attr for --attrs delete a selfservice permission"
		fi

		# Post Test Cleanup:
		ipa selfservice-del $testID > /dev/null 2>&1
		[ -f $tmpout ] && rm $tmpout
		Kcleanup
	rlPhaseEnd
} #selfservice_bz_747741

######################################################################
# ipa selfservice-find --raw returns "internal error"
######################################################################
selfservice_bz_747693()
{
	rlPhaseStartTest "ipa-selfservice-bugzilla-005: bz747693 ipa selfservice-find --raw returns internal error"
                rlRun "rlDistroDiff keyctl"
		KinitAsAdmin
		local testID="selfservice_bz_747693"
		local tmpout=$TmpDir/selfservice_bz_747693.$RANDOM.out
		local attrs_TestValue="l"
		# Pre Test Setup:
		ipa selfservice-add $testID --attrs=l > /dev/null
		# BZ Test:
		rlLog "BZ Test Running: ipa selfservice-find $testID --raw > $tmpout 2>&1"
		ipa selfservice-find $testID --raw > $tmpout 2>&1
		if [ $? -eq 0 ]; then
			rlPass "BZ 747693 not found"
		elif [ $(grep "ipa: ERROR: an internal error has occurred" $tmpout|wc -l) -eq 1 ]; then
			rlFail "BZ 747693 found...ipa selfservice-find --raw returns internal error"
		fi
		# Post Test Cleanup:
		ipa selfservice-del $testID > /dev/null 2>&1
		[ -f $tmpout ] && rm $tmpout
		Kcleanup
	rlPhaseEnd
} #selfservice_bz_747693

######################################################################
# ipa selfservice-find --permission="" returns internal error
######################################################################
selfservice_bz_747720()
{
	rlPhaseStartTest "ipa-selfservice-bugzilla-006: bz747720 ipa selfservice-find --permission=\"\" returns internal error"
                rlRun "rlDistroDiff keyctl"
		KinitAsAdmin
		local testID="selfservice_bz_747720"
		local tmpout=$TmpDir/selfservice_bz_747720.$RANDOM.out
		local attrs_TestValue="l"
		rlLog "BZ Test Running: ipa selfservice-find --permission=\"\" > $tmpout 2>&1"
		ipa selfservice-find --permission="" > $tmpout 2>&1
		if [ $? -eq 0 ]; then
			rlPass "BZ 747720 not found"
		elif [ $(grep "ipa: ERROR: an internal error has occurred" $tmpout|wc -l) -eq 1 ]; then
			rlFail "BZ 747720 found...ipa selfservice-find --permission=\"\" returns internal error"
		fi
		[ -f $tmpout ] && rm $tmpout
		Kcleanup
	rlPhaseEnd
} #selfservice_bz_747720

######################################################################
# ipa selfservice-find --attrs="" returns internal error
######################################################################
selfservice_bz_747722()
{
	rlPhaseStartTest "ipa-selfservice-bugzilla-007: bz747722 ipa selfservice-find --attrs=\"\" returns internal error"
                rlRun "rlDistroDiff keyctl"
		KinitAsAdmin
		local testID="selfservice_bz_747722"
		local tmpout=$TmpDir/selfservice_bz_747722.$RANDOM.out
		local attrs_TestValue="l"
		rlLog "BZ Test Running: ipa selfservice-find --attrs=\"\" > $tmpout 2>&1"
		ipa selfservice-find --attrs="" > $tmpout 2>&1
		if [ $? -eq 0 ]; then
			rlPass "BZ 747722 not found"
		elif [ $(grep "ipa: ERROR: an internal error has occurred" $tmpout|wc -l) -eq 1 ]; then
			rlFail "BZ 747722 found...ipa selfservice-find --attrs=\"\" returns internal error"
		fi
		[ -f $tmpout ] && rm $tmpout
		Kcleanup
	rlPhaseEnd
} #selfservice_bz_747722

#END OF TEST CASE for [selfservice-show]
