package com.redhat.qe.ipa.sahi.tests.group;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Logger;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.redhat.qe.auto.testng.TestNGUtils;
import com.redhat.qe.ipa.sahi.base.SahiTestScript;
import com.redhat.qe.ipa.sahi.tasks.CommonTasks;
import com.redhat.qe.ipa.sahi.tasks.SahiTasks;
import com.redhat.qe.ipa.sahi.tasks.GroupTasks;

public class GroupTests extends SahiTestScript{
	
	private static Logger log = Logger.getLogger(GroupTests.class.getName());
	public static String groupPage = ""; 
	
	
	@BeforeClass (groups={"init"}, description="Initialize app for this test suite run", alwaysRun=true, dependsOnGroups="setup")
	public void initialize() throws CloneNotSupportedException {			
		sahiTasks.navigateTo(commonTasks.groupPage, true);
		sahiTasks.setStrictVisibilityCheck(true);
		
		groupPage = commonTasks.groupPage; 
	}
	
	//TODO: yi: BeforeMethod
	
	/*
	 * Add groups - positive tests
	 */
	@Test (groups={"acceptanceTest"}, dataProvider="getGroupObjects")	
	public void groupAcceptanceTest(String testName, String groupName, String groupDescription) throws Exception {
		GroupTasks.simpleAddGroup(sahiTasks, groupName, groupDescription);
		GroupTasks.addAndAddAnotherGroup(sahiTasks, groupName, groupDescription);
		GroupTasks.addAndEditGroup(sahiTasks, groupName, groupDescription);
		GroupTasks.editGroup(sahiTasks, groupName, groupDescription);
		GroupTasks.membershipGroup(sahiTasks, groupName, groupDescription);
		
		// Notes: Yi Zhang 7.28.2011
		// 1. what is missed: search box inside "enroll dialogbox" and pagenation are missing
		// 2. how to extend current test
		// 	(1) currently, test use only fixed data, to extend, we sholuld apply data driven mechanism
		// 	(2) no negative test here
		// 	(3) no i18n test here
		//
	}//groupAcceptanceTest
	
	/*
	 * Add groups - positive tests
	 */
	@Test (groups={"smokeTest"}, dataProvider="getGroupObjects")	
	public void groupSmokeTest(String testName, String groupName, String groupDescription) throws Exception {

		GroupTasks.smokeTest(sahiTasks);
		 
	}//groupSmokeTest
	
	/*******************************************************
	 ************      DATA PROVIDERS     ***********
	 *******************************************************/

	/*
	 * Data to be used when adding hosts - for positive cases
	 */
	@DataProvider(name="getGroupObjects")
	public Object[][] getGroupObjects() {
		return TestNGUtils.convertListOfListsTo2dArray(createGroupObjects());
	}
	protected List<List<Object>> createGroupObjects() {		
		List<List<Object>> ll = new ArrayList<List<Object>>();
		
        //	test name, groupName, groupDescription				
		ll.add(Arrays.asList(new Object[]{ "addgroup","sahi_auto_001","auto generated by sahi, group 001"} )); 
		        
		return ll;	
	}//createGroupObject
	
}//class GroupTest
