#!/bin/sh

echo "Active Directory user injection starts..."

h=$1
start=$2
end=$3

if [ -z $h ]
then
	echo "pick default: header letter $h"
	h="z"
fi

if [ -z $start ]
then
	echo "pick default: starting uid=100"
	start=100
fi

if [ -z $end ]
then
	echo "pick default: ending uid=120"
	end=120
fi

echo "starting injection, uid header letter [$h], from [$start] to [$end]"

for (( i = $start ; i<= $end ; i++ ))
do
	name="$h"user
	/usr/lib64/mozldap/ldapmodify -h win2003.rhqa.net -p 389 -D "cn=administrator,cn=users,dc=rhqa,dc=net" -w redhat -a -c << _EOF_
dn: CN=$name $i,OU=mmr,DC=rhqa,DC=net
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: $name $i
sn: $i
givenName: $name
displayName: $name $i
description: automatic add by script $i
accountExpires: 9223372036854775807
sAMAccountName: $h$i
userPrincipalName: $h$i@rhqa.net
_EOF_

done

echo "finished. show one user to prove the insertion"
echo "=========== user [$h $end] =================="
/usr/lib*/mozldap/ldapsearch -h win2003.rhqa.net -p 389 -D cn=administrator,cn=users,dc=rhqa,dc=net -w redhat -b dc=rhqa,dc=net "cn=$name *" "dn"
echo "============================================="
echo "warning: you need enable these yourself, i am not be able to do so right now"
echo ""


