#!/bin/sh

uid=$1

if [ -z $uid ]
then
	uid=150
fi

echo "delete uid=[$uid]"

/usr/lib*/mozldap/ldapmodify -h win2003.rhqa.net -p 389 -D "cn=administrator,cn=users,dc=rhqa,dc=net" -w redhat -a -c << _EOF_
dn: CN=auser $uid,OU=mmr,DC=rhqa,DC=net
changetype: delete 
_EOF_

