#!/bin/sh 

uid=$1
field=$2

if [ -z $field ]
then
	field=*
fi

if [ -z $uid ]
then
	echo "ad-finduser <uid>"
else
 /usr/lib*/mozldap/ldapsearch -h win2003.rhqa.net -p 389 -D "cn=administrator,cn=users,dc=rhqa,dc=net" -w redhat -b "dc=rhqa,dc=net" "sAMAccountName=$uid*" "$field" 
fi

