#!/bin/sh

# this is a file that shared by all test script, global vars defined here
USER_FILE=./users.txt
GROUP_FILE=./groups.txt

BEFORE=/tmp/before
AFTER=/tmp/after
CMD_db2ldif=/usr/lib/dirsrv/slapd-*/db2ldif

db=/tmp/db.result
schema=/tmp/schema.result

ADMIN="admin"
FirstName="tuser"
LastName="101"
USER=$FirstName$LastName
GROUP="tgroup101"
PW="redhat123"

VMHOSTER32=giant.dsqa.sjc2.redhat.com
VMHOSTER64=goliath.dsqa.sjc2.redhat.com

########## for 32 bit vms #####################

client32_hoster=$VMHOSTER32
client32_hostname=client32.rhqa.net
client32_imagename="yi-ipa-i386-1"
client32_imagefile=/export/images/yi-ipa-i386-1.img
client32_qa=/export/images/backup/yzhang/snapshot/ipa-i386-1/yi-ipa-i386-1.img.qautil-done-2008-10-01
#client32_ipa10=/export/images/backup/yzhang/snapshot/ipa-i386-1/
client32_ipa11=/export/images/backup/yzhang/snapshot/ipa-i386-1/yi-ipa-i386-1.img.ipa.client.1.1.rpm.installed.but.not.configure

server32_hoster=$VMHOSTER32
server32_hostname=server32.rhqa.net
server32_imagename="yi-ipa-i386-2"
server32_imagefile=/export/images/yi-ipa-i386-2.img
server32_qa=/export/images/backup/yzhang/snapshot/ipa-i386-2/yi-ipa-i386-2.img.qautil.10-17-2008
server32_ipa10=/export/images/backup/yzhang/snapshot/ipa-i386-2/yi-ipa-i386-2.img.10-17-2009-ipa1.0.installed
server32_ipa11=/export/images/backup/yzhang/snapshot/ipa-i386-2/yi-ipa-i386-2.img.10-23-2009-ipa1.1.installed

replica32_hoster=$VMHOSTER32
replica32_hostname=replica32.rhqa.net
replica32_imagename="yi-ipa-i386-3"
replica32_imagefile=/export/images/yi-ipa-i386-3.img
replica32_qa=/export/images/backup/yzhang/snapshot/ipa-i386-3/yi-ipa-i386-3.img.qautil
replica32_ipa10=/export/images/backup/yzhang/snapshot/ipa-i386-3/yi-ipa-i386-3.img.ipa.1.0.release.rpms.installed.but.not.configure
replica32_ipa11=/export/images/backup/yzhang/snapshot/ipa-i386-3/yi-ipa-i386-3.img.ipa.1.1.release.rpms.installed.but.not.configure

########## for 64 bit vms #####################

client64_hoster=$VMHOSTER64
client64_hostname=client64.rhqa.net
client64_imagename=yi-ipa-64-1
client64_imagefile=/export/images/yi-ipa-64-1.img
client64_qa=/export/images/backup/yzhang/snapshots/ipa-64-1/yi-ipa-64-1.img.qautil.ready
client64_ipa10=/export/images/backup/yzhang/snapshots/ipa-64-1/yi-ipa-64-1.img.ipa.1.0.client.installed.but.not.configure
client64_ipa11=/export/images/backup/yzhang/snapshots/ipa-64-1/yi-ipa-64-1.img.ipa.1.1.client.installed.but.not.configure

server64_hoster=$VMHOSTER64
server64_hostname=server64.rhqa.net
server64_imagename=yi-ipa-64-2
server64_imagefile=/export/images/yi-ipa-64-2.img
server64_qa=/export/images/backup/yzhang/snapshots/ipa-64-2/yi-ipa-64-2.img.qautil.10-17-2008
server64_ipa10=/export/images/backup/yzhang/snapshots/ipa-64-2/yi-ipa-64-2.img.10-23-2008.ipa.1.0.installed
server64_ipa11=/export/images/backup/yzhang/snapshots/ipa-64-2/yi-ipa-64-2.img.10-17-2008.ipa.1.1.installed

replica64_hoster=$VMHOSTER64
replica64_hostname=replica64.rhqa.net
replica64_imagename=yi-ipa-64-3
replica64_imagefile=/export/images/yi-ipa-64-3.img
replica64_qa=/export/images/backup/yzhang/snapshots/ipa-64-3/yi-ipa-64-3.img.qautil.10-17-2009
replica64_ipa10=/export/images/backup/yzhang/snapshots/ipa-64-3/yi-ipa-64-3.img.ipa.1.0.release.rpms.installed.but.not.configed
replica64_ipa11=/export/images/backup/yzhang/snapshots/ipa-64-3/yi-ipa-64-3.img.ipa.1.1.release.rpms.installed.but.not.configed

