#!/bin/sh

# this is a file that shared by all test script, global vars defined here
USER_FILE=./users.txt
GROUP_FILE=./groups.txt

BEFORE=/tmp/before
AFTER=/tmp/after
CMD_db2ldif=/usr/lib*/dirsrv/slapd-*/db2ldif

db=/tmp/db.result
schema=/tmp/schema.result

ADMIN="admin"
FirstName="tuser"
LastName="101"
USER=$FirstName$LastName
GROUP="tgroup101"
PW="redhat123"

VMHOSTER32=giant.dsqa.sjc2.redhat.com
VMHOSTER64=goliath.dsqa.sjc2.redhat.com

########## for 32 bit vms #####################

client32_hoster=$VMHOSTER32
client32_hostname=client32.rhqa.net
client32_imagename="yi-ipa-i386-1"
client32_imagefile=/export/images/yi-ipa-i386-1.img
client32_qa=/export/images/backup/yzhang/snapshot/ipa-i386-1/yi-ipa-i386-1.img.qa
client32_ipa10=/export/images/backup/yzhang/snapshot/ipa-i386-1/yi-ipa-i386-1.img.ipa.client.1.0.rpm.installed.but.not.configure
client32_ipa11=/export/images/backup/yzhang/snapshot/ipa-i386-1/yi-ipa-i386-1.img.ipa.client.1.1.rpm.installed.but.not.configure

server32_hoster=$VMHOSTER32
server32_hostname=server32.rhqa.net
server32_imagename="yi-ipa-i386-2"
server32_imagefile=/export/images/yi-ipa-i386-2.img
server32_qa=/export/images/backup/yzhang/snapshot/ipa-i386-2/qa
server32_ipa10=/export/images/backup/yzhang/snapshot/ipa-i386-2/ipaserver10
server32_ipa11=/export/images/backup/yzhang/snapshot/ipa-i386-2/ipaserver11

replica32_hoster=$VMHOSTER32
replica32_hostname=replica32.rhqa.net
replica32_imagename="yi-ipa-i386-3"
replica32_imagefile=/export/images/yi-ipa-i386-3.img
replica32_qa=/export/images/backup/yzhang/snapshot/ipa-i386-3/qa
replica32_ipa10=/export/images/backup/yzhang/snapshot/ipa-i386-3/ipaserver10
replica32_ipa11=/export/images/backup/yzhang/snapshot/ipa-i386-3/ipaserver11

#### rhel 4 32 bit ####
client32_rh4_hoster=$VMHOSTER32
client32_rh4_hostname=rhel432.rhqa.net
client32_rh4_imagename=yi-rhel4-32
client32_rh4_imagefile=/export/images/yi-rhel4-32.img
client32_rh4_qa=/export/images/backup/yzhang/snapshots/rhel432/qa
client32_rh4_ipa10=/export/images/backup/yzhang/snapshots/rhel432/ipaclient10
client32_rh4_ipa11=/export/images/backup/yzhang/snapshots/rhel432/ipaclient11


#### window 2003 server (active directory server) ####
win2003=$VMHOSTER32
win2003_hostname=win2003.rhqa.net
win2003_imagename=win2003
win2003_imagefile=/export/images/win2003.img
win2003_qa=/export/images/backup/yzhang/snapshots/win2003/qa
win2003_ad=/export/images/backup/yzhang/snapshots/win2003/ipaclient10


########## for 64 bit vms #####################

client64_hoster=$VMHOSTER64
client64_hostname=client64.rhqa.net
client64_imagename=yi-ipa-64-1
client64_imagefile=/export/images/yi-ipa-64-1.img
client64_qa=/export/images/backup/yzhang/snapshots/ipa-64-1/yi-ipa-64-1.img.qautil.ready
client64_ipa10=/export/images/backup/yzhang/snapshots/ipa-64-1/yi-ipa-64-1.img.ipa.1.0.client.installed.but.not.configure
client64_ipa11=/export/images/backup/yzhang/snapshots/ipa-64-1/yi-ipa-64-1.img.ipa.1.1.client.installed.but.not.configure

server64_hoster=$VMHOSTER64
server64_hostname=server64.rhqa.net
server64_imagename=yi-ipa-64-2
server64_imagefile=/export/images/yi-ipa-64-2.img
server64_qa=/export/images/backup/yzhang/snapshots/ipa-64-2/qa
server64_ipa10=/export/images/backup/yzhang/snapshots/ipa-64-2/ipaserver10
server64_ipa11=/export/images/backup/yzhang/snapshots/ipa-64-2/ipaserver11

replica64_hoster=$VMHOSTER64
replica64_hostname=replica64.rhqa.net
replica64_imagename=yi-ipa-64-3
replica64_imagefile=/export/images/yi-ipa-64-3.img
replica64_qa=/export/images/backup/yzhang/snapshots/ipa-64-3/qa
replica64_ipa10=/export/images/backup/yzhang/snapshots/ipa-64-3/ipaserver10
replica64_ipa11=/export/images/backup/yzhang/snapshots/ipa-64-3/ipaserver11

#### rhel 4 64 bit ###
client64_rh4_hoster=$VMHOSTER64
client64_rh4_hostname=rhel464.rhqa.net
client64_rh4_imagename=yi-ipa-rhel464
client64_rh4_imagefile=/export/images/yi-rhel4-64.img
client64_rh4_qa=/export/images/backup/yzhang/snapshots/ipa-rhel464/qa
client64_rh4_ipa10=/export/images/backup/yzhang/snapshots/ipa-rhel464/ipaclient10
client64_rh4_ipa11=/export/images/backup/yzhang/snapshots/ipa-rhel464/ipaclient11
