#!/bin/sh

. ./env
. ./libs.sh

echo "IPA update mechanism test starts..." > $LOGFILE


testcase_1()
{
	IPASERVER=$SERVER32
	LOG "stand alone ipa server upgrade : rhel 5, i386"
	LOG "machine to use [$IPASERVER]"
	BEFORE=$TESTDIR/before
	AFTER=$TESTDIR/after
	mkdir $BEFORE
	mkdir $AFTER
	setup_ipaserver    $IPASERVER
	inject_data        $IPASERVER
	save_data          $IPASERER $BEFORE
	update_ipaserver   $IPASERVER
	save_data          $IPASERVER $AFTER
	verify_ipaserver_function   $IPASERVER	
	verify_ipaserver_data       $IPASERVER BEFORE AFTER
	LOG "TEST CASE 1 finished"
}

testcase_2()
{
	IPASERVER=$SERVER64 
	LOG "stand alone ipa server upgrade : rhel 5, x86_64"
	LOG "machine to use [$IPASERVER]"
}

testcase_3()
{
	IPASERVER=$SERVER32
	IPAREPLICA=$REPLICA64
	LOG "master-replica IPA topology : rhel 5 i386 master + rhel 5 x84_64"
	LOG "machine to use [$IPASERVER]"
	LOG "machine to use [$IPAREPLICA]"
}

testcase_4()
{
	IPASERVER=$SERVER64
	IPAREPLICA=$REPLICA32
	LOG "master-replica IPA topology : rhel 5 i386 master + rhel 5 x84_64"
	LOG "machine to use [$IPASERVER]"
	LOG "machine to use [$IPAREPLICA]"
}

echo "IPA update mechanism test finished" >> $LOGFILE
