#!/bin/bash -x
#testsuite : ipa-getcert
#author    : 
#testplan  : IPA client tool ipa-getcert Test Plan
#testplan version: 
#last update time: 2006-04-26 14:20:27
#sequence number : 1

ipagetcert_extended() #total test cases: 14 
{
    request_extended
    start_tracking_extended
    stop_tracking_extended
    resubmit_extended
    list_extended
} #ipagetcert

list_extended()
{ #total test cases: 8
    rlPhaseStartTest "ipa-getcert list functionality Test 001 - Listing certificates by listening on System bus (-S switch)"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"  #Chaning SELinux security context of temp directory so that key-pair can be generated
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "Certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list -S >$TmpDir/temp_test001.out" 
       rlRun "cat $TmpDir/temp_test001.out" 
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test001.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd
    
    rlPhaseStartTest "ipa-getcert list functionality Test 002 - Listing only one cert on providing NSS db and nickname"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"  #Chaning SELinux security context of temp directory so that key-pair can be generated
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "Certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list -d $TmpDir -n certtest > $TmpDir/temp_test002.out"
       rlRun "cat $TmpDir/temp_test002.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test002.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert list functionality Test 003 - Listing only one cert on providing file storage path"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"  #Chaning SELinux security context of temp directory so that key-pair can be generated
       rlRun "ipa-getcert request -f $TmpDir/test.crt -k $TmpDir/test.key  " 0 "Certificate generated"
       rlRun "sleep 10"
       rlRun "ipa-getcert list -f $TmpDir/test.crt > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test003.out"
       rlRun "ipa-getcert stop-tracking -f $TmpDir/test.crt -k $TmpDir/test.key"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd
     
    rlPhaseStartTest "ipa-getcert list functionality Test 004 - Listing only one cert on providing request identifier"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"  #Chaning SELinux security context of temp directory so that key-pair can be generated
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "Certificate generated"
       rlRun "sleep 30"
       rlRun "ipa-getcert list -i testing > $TmpDir/temp_test004.out"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test004.out"
       rlRun "ipa-getcert stop-tracking -i testing"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd 

    rlPhaseStartTest "ipa-getcert list functionality Test 005 - output on providing non-existent request identifier" 
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"  #Chaning SELinux security context of temp directory so that key-pair can be generated
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "Certificate generated"
       rlRun "sleep 10"
       rlRun "ipa-getcert list -i non-existent > $TmpDir/temp_test005.out" 1
       rlRun "cat $TmpDir/temp_test005.out"
       rlAssertGrep "No request found with specified nickname." "$TmpDir/temp_test005.out"
       rlRun "ipa-getcert stop-tracking -i testing"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert list functionality Test 006 -  output on providing non-existent file storage path" 
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"  #Chaning SELinux security context of temp directory so that key-pair can be generated
       rlRun "ipa-getcert request -f $TmpDir/test.crt -k $TmpDir/test.key  " 0 "Certificate generated"
       rlRun "sleep 6"
       rlRun "ipa-getcert list -f $TmpDir/non-existent.crt > $TmpDir/temp_test006.out" 1
       rlRun "cat $TmpDir/temp_test006.out"
       rlAssertGrep "No request found that matched arguments." "$TmpDir/temp_test006.out"
       rlRun "ipa-getcert stop-tracking -f $TmpDir/test.crt -k $TmpDir/test.key"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert list functionality Test 007 - output on providing incorrect NSS db and correct nickname" 
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"  #Chaning SELinux security context of temp directory so that key-pair can be generated
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "Certificate generated"
       rlRun "sleep 10"
       rlRun "ipa-getcert list -d /tmp/non-existent -n certtest > $TmpDir/temp_test007.out" 1
       rlRun "cat $TmpDir/temp_test007.out"
       rlAssertGrep "Path \"/tmp/non-existent\": No such file or directory." "$TmpDir/temp_test007.out"
       rlRun "ipa-getcert stop-tracking -i testing"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

   rlPhaseStartTest "ipa-getcert list functionality Test 008 - output on providing correct NSS db and incorrect nickname" 
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"  #Chaning SELinux security context of temp directory so that key-pair can be generated
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "Certificate generated"
       rlRun "sleep 10"
       rlRun "ipa-getcert list -d $TmpDir -n non-existent > $TmpDir/temp_test008.out" 1
       rlRun "cat $TmpDir/temp_test008.out"
       rlAssertGrep "No request found that matched arguments." "$TmpDir/temp_test008.out"
       rlRun "ipa-getcert stop-tracking -i testing"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

}

request_extended()
{ #total test cases:6 
    rlPhaseStartTest "ipa-getcert request functionality Test 001 -Request using NSS database for storage with PIN value(-P switch) --Positive"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "echo "" >$TmpDir/oldpasswdfile_001.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_001.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_001.txt"
       rlRun "certutil -N -d $TmpDir -f $TmpDir/oldpasswdfile_001.txt -@ $TmpDir/newpasswdfile_001.txt"
       rlRun "certutil -N -d $TmpDir -f $TmpDir/oldpasswdfile_001.txt -@ $TmpDir/newpasswdfile_001.txt"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -P \"temp123#\"" 0 "Certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out"
       rlRun "cat $TmpDir/temp_test001.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test001.out"
       rlAssertGrep "pin='temp123#'" "$TmpDir/temp_test001.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert request functionality Test 002 -Request using NSS database for storage and with password file (-p switch) --Positive"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "echo "" >$TmpDir/oldpasswdfile_002.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_002.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_002.txt"
       rlRun "certutil -N -d $TmpDir -f $TmpDir/oldpasswdfile_002.txt -@ $TmpDir/newpasswdfile_002.txt"
       rlRun "certutil -N -d $TmpDir -f $TmpDir/oldpasswdfile_002.txt -@ $TmpDir/newpasswdfile_002.txt"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -p $TmpDir/newpasswdfile_002.txt" 0 "Certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test002.out"
       rlRun "cat $TmpDir/temp_test002.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test002.out"
       rlAssertGrep "newpasswdfile_002.txt" "$TmpDir/temp_test002.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert request functionality Test 003 - Request using NSS db for storage and empty/incorrect PIN (-P switch) --Negative" 
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "echo "" >$TmpDir/oldpasswdfile_003.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_003.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_003.txt"
       rlRun "certutil -N -d $TmpDir -f $TmpDir/oldpasswdfile_003.txt -@ $TmpDir/newpasswdfile_003.txt"
       rlRun "certutil -N -d $TmpDir -f $TmpDir/oldpasswdfile_003.txt -@ $TmpDir/newpasswdfile_003.txt"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -P > $TmpDir/temp_test003.out 2>&1" 1
       rlAssertGrep "request: option requires an argument -- 'P'" "$TmpDir/temp_test003.out"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -P \"wrong\" "  
       rlRun "sleep 5"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "NEWLY_ADDED_NEED_KEYINFO_READ_PIN" "$TmpDir/temp_test003.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert request functionality Test 004 - Request using files for storage and empty/incorrect password file (-p switch) --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -p > $TmpDir/temp_test004.out 2>&1" 1
       rlRun "sleep 6"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "request: option requires an argument -- 'p'" "$TmpDir/temp_test004.out"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -p $TmpDir/non-existent.txt"
       rlRun "ipa-getcert list > $TmpDir/temp_test004.out"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "NEWLY_ADDED_NEED_KEYINFO_READ_PIN" "$TmpDir/temp_test004.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test004.out"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existent.txt\": No such file or directory." "$TmpDir/temp_test004.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert request functionality Test 005 -Request using NSS database for storage and with password file with incorrect PIN(-p switch) --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "echo "" >$TmpDir/oldpasswdfile_005.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_005.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_005.txt"
       rlRun "certutil -N -d $TmpDir -f $TmpDir/oldpasswdfile_005.txt -@ $TmpDir/newpasswdfile_005.txt"
       rlRun "certutil -N -d $TmpDir -f $TmpDir/oldpasswdfile_005.txt -@ $TmpDir/newpasswdfile_005.txt"
       rlRun "echo "temp123" >$TmpDir/newpasswdfile_005.txt"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -p $TmpDir/newpasswdfile_005.txt" 0 "Certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test005.out"
       rlRun "cat $TmpDir/temp_test005.out"
       rlAssertGrep ""NEWLY_ADDED_NEED_KEYINFO_READ_PIN"" "$TmpDir/temp_test005.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert request functionality Test 006 - Request using files for storage and empty request name (-I switch) --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I > $TmpDir/temp_test006.out 2>&1" 1
       rlRun "sleep 6"
       rlRun "cat $TmpDir/temp_test006.out "
       rlAssertGrep "request: option requires an argument -- 'I'" "$TmpDir/temp_test006.out"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert request functionality Test 007 - Request using NSS db with non-existent token (-t switch) --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -t non-existent> $TmpDir/temp_test007.out 2>&1" 0
       rlRun "sleep 6"
       rlRun "ipa-getcert list > $TmpDir/temp_test007.out"
       rlRun "cat $TmpDir/temp_test007.out"
       rlAssertGrep ""NEWLY_ADDED_NEED_KEYINFO_READ_TOKEN"" "$TmpDir/temp_test007.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd
}

resubmit_extended()
{ #total test cases: 6
    rlPhaseStartTest "ipa-getcert resubmit functionality Test 001 - Resubmit request when correct PIN is provided (-P switch) --Positive"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" #this is because certmonger does not have write permission on /tmp dir.
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out" 
       rlRun "cat $TmpDir/temp_test001.out" 
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test001.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test001.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test001.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test001.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test001.txt"
       rlRun "cat $TmpDir/newpasswdfile_test001.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test001.txt -@ $TmpDir/newpasswdfile_test001.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -P temp123" 0 "Request resubmitted"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out"
       rlRun "cat $TmpDir/temp_test001.out" 
       rlAssertGrep "pin='temp123'" "$TmpDir/temp_test001.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test001.out"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -P temp123#" 0 "Request resubmitted successfully"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out" 
       rlRun "cat $TmpDir/temp_test001.out" 
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test001.out"
       rlAssertGrep "pin='temp123#'" "$TmpDir/temp_test001.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd


    rlPhaseStartTest "ipa-getcert resubmit functionality Test 002 - Resubmit request when incorrect PIN is provided (-P switch) --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" #this is because certmonger does not have write permission on /tmp dir.
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test002.out" 
       rlRun "cat $TmpDir/temp_test002.out" 
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test002.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test002.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test002.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test002.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test002.txt"
       rlRun "cat $TmpDir/newpasswdfile_test002.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test002.txt -@ $TmpDir/newpasswdfile_test002.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -P temp123" 0 "Request resubmitted"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test002.out"
       rlRun "cat $TmpDir/temp_test002.out" 
       rlAssertGrep "pin='temp123'" "$TmpDir/temp_test002.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test002.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert resubmit functionality Test 003 - Resubmit request when correct password file is provided (-p switch) --Positive"

       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" #this is because certmonger does not have write permission on /tmp dir.
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test003.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test003.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test003.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test003.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test003.txt -@ $TmpDir/newpasswdfile_test003.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -p $TmpDir/non-existentfile.txt" 0 "Request resubmitted"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "non-existentfile.txt" "$TmpDir/temp_test003.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test003.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test003.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existentfile.txt\": No such file or directory." "$TmpDir/temp_test003.out"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test003.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -p $TmpDir/newpasswdfile_test003.txt" 0 "Request resubmitted"
       rlRun "sleep 10"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test003.out"
       rlAssertGrep "newpasswdfile_test003.txt" "$TmpDir/temp_test003.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"

    rlPhaseEnd 

    rlPhaseStartTest "ipa-getcert resubmit functionality Test 004 - Resubmit request when incorrect password file is provided (-p switch) --Negative"

       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" #this is because certmonger does not have write permission on /tmp dir.
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test004.out"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test004.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test004.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test004.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test004.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test004.txt -@ $TmpDir/newpasswdfile_test004.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -p $TmpDir/non-existentfile.txt" 0 "Request resubmitted"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test004.out"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "non-existentfile.txt" "$TmpDir/temp_test004.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test004.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test004.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existentfile.txt\": No such file or directory." "$TmpDir/temp_test004.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"

    rlPhaseEnd 

    rlPhaseStartTest "ipa-getcert resubmit functionality Test 005 - Resubmit request when incorrect token name is provided (-t switch) --Negative"

       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" #this is because certmonger does not have write permission on /tmp dir.
       rlRun "ipa-getcert request -d $TmpDir -n certtest -t \"NSS Certificate DB\"" 0 "certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test005.out"
       rlRun "cat $TmpDir/temp_test005.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test005.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test005.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test005.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test005.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test005.txt -@ $TmpDir/newpasswdfile_test005.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -p $TmpDir/newpasswdfile_test005.txt -t non-existent > $TmpDir/temp_test005.out 2>&1" 1  
       rlRun "cat $TmpDir/temp_test005.out"
       rlAssertGrep "No request found that matched arguments." "$TmpDir/temp_test005.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"

    rlPhaseEnd 

    rlPhaseStartTest "ipa-getcert resubmit functionality Test 006 - Resubmit request when incorrect password is given in password file provided (-p switch) --Negative"

       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" #this is because certmonger does not have write permission on /tmp dir.
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test006.out"
       rlRun "cat $TmpDir/temp_test006.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test006.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test006.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test006.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test006.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test006.txt -@ $TmpDir/newpasswdfile_test006.txt"
       rlRun "echo "temp123" >$TmpDir/newpasswdfile_test006.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -p $TmpDir/newpasswdfile_test006.txt" 0 "Request resubmitted"
       rlRun "sleep 10"
       rlRun "ipa-getcert list > $TmpDir/temp_test006.out"
       rlRun "cat $TmpDir/temp_test006.out"
       rlAssertGrep "NEED_CSR_GEN_PIN" "$TmpDir/temp_test006.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd 
}

start_tracking_extended()
{ #total test cases:
   rlPhaseStartTest "ipa-getcert start-tracking functionality Test 001 - start-tracking request when correct PIN is provided (-P switch) --Positive"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" 
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 30"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out"
       rlRun "cat $TmpDir/temp_test001.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test001.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test001.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test001.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test001.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test001.txt"
       rlRun "cat $TmpDir/newpasswdfile_test001.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test001.txt -@ $TmpDir/newpasswdfile_test001.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -P temp123"
       rlRun "sleep 30"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out"
       rlRun "cat $TmpDir/temp_test001.out"
       rlAssertGrep "pin='temp123'" "$TmpDir/temp_test001.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test001.out"
       rlRun "ipa-getcert start-tracking -d $TmpDir -n certtest -P temp123#"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out"
       rlRun "cat $TmpDir/temp_test001.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test001.out"
       rlAssertGrep "pin='temp123#'" "$TmpDir/temp_test001.out"
       rlAssertGrep "track: yes" "$TmpDir/temp_test001.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

   rlPhaseStartTest "ipa-getcert start-tracking functionality Test 002 - start-tracking request when incorrect PIN is provided (-P switch) --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" 
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 30"
       rlRun "ipa-getcert list > $TmpDir/temp_test002.out"
       rlRun "cat $TmpDir/temp_test002.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test002.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test002.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test002.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test002.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test002.txt"
       rlRun "cat $TmpDir/newpasswdfile_test002.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test002.txt -@ $TmpDir/newpasswdfile_test002.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -P temp123"
       rlRun "sleep 30"
       rlRun "ipa-getcert list > $TmpDir/temp_test002.out"
       rlRun "cat $TmpDir/temp_test002.out"
       rlAssertGrep "pin='temp123'" "$TmpDir/temp_test002.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test002.out"
       rlRun "ipa-getcert start-tracking -d $TmpDir -n certtest -P temp123"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test002.out"
       rlRun "cat $TmpDir/temp_test002.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test002.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert start-tracking functionality Test 003 - start-tracking request when correct password file is provided (-p switch) --Positive"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test003.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test003.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test003.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test003.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test003.txt"
       rlRun "cat $TmpDir/newpasswdfile_test003.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test003.txt -@ $TmpDir/newpasswdfile_test003.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -p $TmpDir/non-existentfile.txt" 0 "Request resubmitted"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "non-existentfile.txt" "$TmpDir/temp_test003.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test003.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test003.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existentfile.txt\": No such file or directory." "$TmpDir/temp_test003.out"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test003.txt"
       rlRun "cat $TmpDir/newpasswdfile_test003.txt"
       rlRun "ipa-getcert start-tracking -d $TmpDir -n certtest -p $TmpDir/newpasswdfile_test003.txt"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test003.out"
       rlAssertGrep "newpasswdfile_test003.txt" "$TmpDir/temp_test003.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert start-tracking functionality Test 004 - start-tracking request when pinfile is having wrong pin (-p switch) --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test004.out"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test004.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test004.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test004.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test004.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test004.txt"
       rlRun "cat $TmpDir/newpasswdfile_test004.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test004.txt -@ $TmpDir/newpasswdfile_test004.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -p $TmpDir/non-existentfile.txt" 0 "Request resubmitted"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test004.out"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "non-existentfile.txt" "$TmpDir/temp_test004.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test004.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test004.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existentfile.txt\": No such file or directory." "$TmpDir/temp_test004.out"
       rlRun "echo "temp123#@" >$TmpDir/newpasswdfile_test004.txt"
       rlRun "cat $TmpDir/newpasswdfile_test004.txt"
       rlRun "ipa-getcert start-tracking -d $TmpDir -n certtest -p $TmpDir/newpasswdfile_test004.txt"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test004.out"
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test004.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert start-tracking functionality Test 005 - start-tracking request when incorrect PIN file is provided (-p switch) --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest" 0 "certificate generated"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test005.out"
       rlRun "cat $TmpDir/temp_test005.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test005.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test005.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test005.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test005.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test005.txt"
       rlRun "cat $TmpDir/newpasswdfile_test005.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test005.txt -@ $TmpDir/newpasswdfile_test005.txt"
       rlRun "ipa-getcert resubmit -d $TmpDir -n certtest -p $TmpDir/non-existentfile.txt" 0 "Request resubmitted"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test005.out"
       rlRun "cat $TmpDir/temp_test005.out"
       rlAssertGrep "non-existentfile.txt" "$TmpDir/temp_test005.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test005.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test005.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existentfile.txt\": No such file or directory." "$TmpDir/temp_test005.out"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test005.txt"
       rlRun "cat $TmpDir/newpasswdfile_test005.txt"
       rlRun "ipa-getcert start-tracking -d $TmpDir -n certtest -p $TmpDir/non-existentfile.txt"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test005.out"
       rlRun "cat $TmpDir/temp_test005.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test005.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd
   rlPhaseStartTest "ipa-getcert start-tracking functionality Test 006 - start-tracking request when correct PIN is provided (-P switch) with request identifier --Positive"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" 
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "certificate generated"
       rlRun "sleep 30"
       rlRun "ipa-getcert list > $TmpDir/temp_test006.out"
       rlRun "cat $TmpDir/temp_test006.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test006.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test006.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test006.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test006.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test006.txt"
       rlRun "cat $TmpDir/newpasswdfile_test006.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test006.txt -@ $TmpDir/newpasswdfile_test006.txt"
       rlRun "ipa-getcert resubmit -i testing -P temp123"
       rlRun "sleep 30"
       rlRun "ipa-getcert list > $TmpDir/temp_test006.out"
       rlRun "cat $TmpDir/temp_test006.out"
       rlAssertGrep "pin='temp123'" "$TmpDir/temp_test006.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test006.out"
       rlRun "ipa-getcert start-tracking -i testing -P temp123#"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test006.out"
       rlRun "cat $TmpDir/temp_test006.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test006.out"
       rlAssertGrep "pin='temp123#'" "$TmpDir/temp_test006.out"
       rlAssertGrep "track: yes" "$TmpDir/temp_test006.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

   rlPhaseStartTest "ipa-getcert start-tracking functionality Test 007 - start-tracking request when incorrect PIN is provided (-P switch) with request identifier --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir" 
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "certificate generated"
       rlRun "sleep 30"
       rlRun "ipa-getcert list > $TmpDir/temp_test007.out"
       rlRun "cat $TmpDir/temp_test007.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test007.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test007.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test007.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test007.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test007.txt"
       rlRun "cat $TmpDir/newpasswdfile_test007.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test007.txt -@ $TmpDir/newpasswdfile_test007.txt"
       rlRun "ipa-getcert resubmit -i testing -P temp123"
       rlRun "sleep 30"
       rlRun "ipa-getcert list > $TmpDir/temp_test007.out"
       rlRun "cat $TmpDir/temp_test007.out"
       rlAssertGrep "pin='temp123'" "$TmpDir/temp_test007.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test007.out"
       rlRun "ipa-getcert start-tracking -i testing -P temp123"
       rlRun "sleep 20"
       rlRun "ipa-getcert list > $TmpDir/temp_test007.out"
       rlRun "cat $TmpDir/temp_test007.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test007.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

     rlPhaseStartTest "ipa-getcert start-tracking functionality Test 008 - start-tracking request when correct password file is provided (-p switch) with request identifier --Positive"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "certificate generated"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test008.out"
       rlRun "cat $TmpDir/temp_test008.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test008.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test008.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test008.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test008.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test008.txt"
       rlRun "cat $TmpDir/newpasswdfile_test008.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test008.txt -@ $TmpDir/newpasswdfile_test008.txt"
       rlRun "ipa-getcert resubmit -i testing -p $TmpDir/non-existentfile.txt" 0 "Request resubmitted"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test008.out"
       rlRun "cat $TmpDir/temp_test008.out"
       rlAssertGrep "non-existentfile.txt" "$TmpDir/temp_test008.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test008.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test008.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existentfile.txt\": No such file or directory." "$TmpDir/temp_test008.out"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test008.txt"
       rlRun "cat $TmpDir/newpasswdfile_test008.txt"
       rlRun "ipa-getcert start-tracking -i testing -p $TmpDir/newpasswdfile_test008.txt"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test008.out"
       rlRun "cat $TmpDir/temp_test008.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test008.out"
       rlAssertGrep "newpasswdfile_test008.txt" "$TmpDir/temp_test008.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert start-tracking functionality Test 009 - start-tracking request when incorrect PIN file path is provided (-p switch) with request identifier --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "certificate generated"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test009.out"
       rlRun "cat $TmpDir/temp_test009.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test009.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test009.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test009.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test009.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test009.txt"
       rlRun "cat $TmpDir/newpasswdfile_test009.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test009.txt -@ $TmpDir/newpasswdfile_test009.txt"
       rlRun "ipa-getcert resubmit -i testing -p $TmpDir/non-existentfile.txt" 0 "Request resubmitted"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test009.out"
       rlRun "cat $TmpDir/temp_test009.out"
       rlAssertGrep "non-existentfile.txt" "$TmpDir/temp_test009.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test009.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test009.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existentfile.txt\": No such file or directory." "$TmpDir/temp_test009.out"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test009.txt"
       rlRun "cat $TmpDir/newpasswdfile_test009.txt"
       rlRun "ipa-getcert start-tracking -i testing -p $TmpDir/non-existentfile.txt"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test009.out"
       rlRun "cat $TmpDir/temp_test009.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test009.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert start-tracking functionality Test 010 - start-tracking request when PIN file is having incorrect PIN (-p switch) with request identifier --Negative"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "certificate generated"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test010.out"
       rlRun "cat $TmpDir/temp_test010.out"
       rlAssertGrep "status: MONITORING" "$TmpDir/temp_test010.out"
       rlRun "echo "" >$TmpDir/oldpasswdfile_test010.txt"
       rlRun "echo "temp123#" >$TmpDir/newpasswdfile_test010.txt"
       rlRun "echo "temp123#" >>$TmpDir/newpasswdfile_test010.txt"
       rlRun "cat $TmpDir/oldpasswdfile_test010.txt"
       rlRun "cat $TmpDir/newpasswdfile_test010.txt"
       rlRun "certutil -W -d $TmpDir -f $TmpDir/oldpasswdfile_test010.txt -@ $TmpDir/newpasswdfile_test010.txt"
       rlRun "ipa-getcert resubmit -i testing -p $TmpDir/non-existentfile.txt" 0 "Request resubmitted"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test010.out"
       rlRun "cat $TmpDir/temp_test010.out"
       rlAssertGrep "non-existentfile.txt" "$TmpDir/temp_test010.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test010.out"
       rlRun "tail -5 /var/log/messages > $TmpDir/temp_test010.out"
       rlAssertGrep "certmonger: Error reading PIN from \"$TmpDir/non-existentfile.txt\": No such file or directory." "$TmpDir/temp_test010.out"
       rlRun "echo "temp123" >$TmpDir/newpasswdfile_test010.txt"
       rlRun "cat $TmpDir/newpasswdfile_test010.txt"
       rlRun "ipa-getcert start-tracking -i testing -p $TmpDir/newpasswdfile_test010.txt"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test010.out"
       rlRun "cat $TmpDir/temp_test010.out"
       rlAssertGrep "status: NEED_CSR_GEN_PIN" "$TmpDir/temp_test010.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd
}

stop_tracking_extended()
{ #total test cases: 4
    rlPhaseStartTest "ipa-getcert stop-tracking functionality Test 001 - stops tracking request on providing NSS database path and certificate nickname"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -I testing" 0 "certificate generated successfully"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out"
       rlRun "cat $TmpDir/temp_test001.out"
       rlAssertGrep "MONITORING" "$TmpDir/temp_test001.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest" 0 "request tracking stopped successfully"
       rlRun "ipa-getcert list > $TmpDir/temp_test001.out"
       rlRun "cat $TmpDir/temp_test001.out"
       rlAssertGrep "Number of certificates and requests being tracked: 0." "$TmpDir/temp_test001.out"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd 

    rlPhaseStartTest "ipa-getcert stop-tracking functionality Test 002 -stops tracking request on providing certificate and key file path"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -f $TmpDir/certtest -k $TmpDir/certtest.key -I testing" 0 "certificate generated successfully"
       rlRun "sleep 6"
       rlRun "ipa-getcert list > $TmpDir/temp_test002.out"
       rlRun "cat $TmpDir/temp_test002.out"
       rlAssertGrep "MONITORING" "$TmpDir/temp_test002.out"
       rlRun "ipa-getcert stop-tracking -f $TmpDir/certtest -k $TmpDir/certtest.key"
       rlRun "ipa-getcert list > $TmpDir/temp_test002.out"
       rlRun "cat $TmpDir/temp_test002.out"
       rlAssertGrep "Number of certificates and requests being tracked: 0." "$TmpDir/temp_test002.out"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd

    rlPhaseStartTest "ipa-getcert stop-tracking functionality Test 003 - stops tracking request on providing NSS database path and certificate nickname"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert request -d $TmpDir -n certtest -t \"NSS Certificate DB\" -I testing" 0 "certificate generated successfully"
       rlRun "sleep 15"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "MONITORING" "$TmpDir/temp_test003.out"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest -t \"NSS Certificate DB\" " 0 "request tracking stopped successfully"
       rlRun "ipa-getcert list > $TmpDir/temp_test003.out"
       rlRun "cat $TmpDir/temp_test003.out"
       rlAssertGrep "Number of certificates and requests being tracked: 0." "$TmpDir/temp_test003.out"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd 

    rlPhaseStartTest "ipa-getcert stop-tracking functionality Test 004 - stops tracking request on providing NSS database path and certificate nickname"
       rlRun "TmpDir=\`mktemp -d\`" 0 "Creating tmp directory"
       rlRun "sleep 4"
       rlRun "chcon -t cert_t $TmpDir"
       rlRun "ipa-getcert stop-tracking -d $TmpDir -n certtest -t non-existent > $TmpDir/temp_test004.out 2>&1" 1
       rlRun "cat $TmpDir/temp_test004.out"
       rlAssertGrep "No request found that matched arguments." "$TmpDir/temp_test004.out"
       rlRun "rm -rf $TmpDir"
    rlPhaseEnd
}
