#!/usr/bin/expect
# vim: dict=/usr/share/beakerlib/dictionary.vim cpt=.,w,b,u,t,i,k
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   Author: Steeve Goveas <stv@redhat.com>
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   Copyright (c) 2010 Red Hat, Inc. All rights reserved.
#
#   This copyrighted material is made available to anyone wishing
#   to use, modify, copy, or redistribute it subject to the terms
#   and conditions of the GNU General Public License version 2.
#
#   This program is distributed in the hope that it will be
#   useful, but WITHOUT ANY WARRANTY; without even the implied
#   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
#   PURPOSE. See the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public
#   License along with this program; if not, write to the Free
#   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301, USA.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

set action [lrange $argv 0 0]
set adusernm [lrange $argv 1 1]
set adpasswd  [lrange $argv 2 2]
set adhostip [lrange $argv 3 3]
set addomain [lrange $argv 4 4]
set ipaadmin [lrange $argv 5 5]
set ipapasswd [lrange $argv 6 6]
set ipadomain [lrange $argv 7 7]

set timeout 20

if { [string compare $action remove ] == 0 } {
# Telnet to the server
spawn telnet $adhostip;
expect "login: ";
send -- "$adusernm\r";
expect "*?assword:*";
send -- "$adpasswd\r";
expect "*>";
send -- "netdom trust $addomain /d:$ipadomain /remove /oneside:trusting /ud:$ipadomain\\$ipaadmin /pd:$ipapasswd /verbose\r";
expect "The command completed successfully." { expect "*>"};
sleep 2;
send -- "netdom trust $ipadomain /d:$addomain /remove /oneside:trusted /ud:$addomain\\$adusernm /pd:$adpasswd /verbose\r";
expect "The command completed successfully."
sleep 2;
send -- "exit\r";
expect eof;
} else {
  puts "Usage: $argv0 remove ADadmin ADpswd ADhostip ADdomain IPAadmin IPApasswd IPAdomain";
}
