#!/bin/bash
# By  : Automatic Generated by at.3.testcase.pl
# Date: Mon Feb 28 10:07:10 2011

#############################################
#  test suite: ipa-join (test cases)
#############################################
ipaotp()
{
    ipa_otp_envsetup
    ipa_otp_1001
    ipa_otp_1002
    ipa_otp_1003
    ipa_otp_1004
    ipa_otp_envcleanup
} #ipaotp

ipa_otp_envsetup()
{
    rlPhaseStartSetup "ipa_otp_envsetup"
        #environment setup starts here
        rlRun "ssh -o StrictHostKeyChecking=no root@$serverFQDN \"echo $ADMINPW | kinit $ADMINID\" " 0 "kinit at remote ipa server as admin"
        rlRun "ssh -o StrictHostKeyChecking=no root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "we have to un-join before test starts"
        rlRun "ssh -o StrictHostKeyChecking=no root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP\"" 0 "add host back to ipa server and set OTP to [$OTP]"
        #environment setup ends   here
    rlPhaseEnd
} #envsetup

ipa_otp_envcleanup()
{
    rlPhaseStartCleanup "ipa_otp_envcleanup"
        #environment cleanup starts here
        rlRun "ssh -o StrictHostKeyChecking=no root@$serverFQDN \"kdestroy\"" 0 "remove kerboros ticket in remote server"
        #environment cleanup ends   here
    rlPhaseEnd
} #envcleanup

ipa_otp_1001()
{
    rlPhaseStartTest "ipa_otp_1001: negative, no OTP password provided" 
        local testID="ipa_otp_1001"
        local tmpout=$TmpDir/ipa_otp_1001.$RANDOM.out
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local bindpw_TestValue_Negative="" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        qaRun "ipa-join --hostname=$hostname_TestValue  --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [bindpw]=[$bindpw_TestValue_Negative]" 
        rm $tmpout
    rlPhaseEnd
} #ipa_otp_1001

ipa_otp_1002()
{
    rlPhaseStartTest "ipa_otp_1002: negative, wrong OTP password provided" 
        local testID="ipa_otp_1002"
        local tmpout=$TmpDir/ipa_otp_1001.$RANDOM.out
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local bindpw_TestValue_Negative="WrongPassword" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        qaRun "ipa-join --hostname=$hostname_TestValue  --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [bindpw]=[$bindpw_TestValue_Negative]" 
        rm $tmpout
    rlPhaseEnd
} #ipa_otp_1002

ipa_otp_1003()
{
    rlPhaseStartTest "ipa_otp_1003 [positive test] --hostname;positive;FQDN --bindpw;positive;ValidPW"
        local testID="ipa_otp_1003"
        local tmpout=$TmpDir/ipa_otp_1003.$RANDOM.out
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        rlRun "ipa-join --hostname=$hostname_TestValue  --bindpw=$OTP" 0 "test options:  [hostname]=[$hostname_TestValue] [bindpw]=[$bindpw_TestValue]" 
        rm $tmpout
    rlPhaseEnd
} #ipa_otp_1003

ipa_otp_1004()
{
    rlPhaseStartTest "ipa_otp_1004 [negative test] use same OTP second time should fail"
        local testID="ipa_otp_1004"
        local tmpout=$TmpDir/ipa_otp_1004.$RANDOM.out
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        qaRun "ipa-join --hostname=$hostname_TestValue  --bindpw=$OTP" "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [bindpw]=[$OTP]" 
        rm $tmpout
    rlPhaseEnd
} #ipa_otp_1004

