#!/bin/bash
# By  : Automatic Generated by at.3.testcase.pl
# Date: Mon Feb 28 10:07:10 2011

#############################################
#  test suite: ipa-join (44 test cases)
#############################################
ipajoin()
{
    ipa_join_envsetup
    ipa_join_1001  #test_scenario (positive test): [--unenroll]
    ipa_join_1011  #test_scenario (positive test): [--hostname;positive;FQDN]
    ipa_join_1012  #test_scenario (negative test): [--hostname;positive;FQDN --bindpw;negative;InvalidPW]
    ipa_join_1013  #test_scenario (positive test): [--hostname;positive;FQDN --bindpw;positive;ValidPW]
    ipa_join_1016  #test_scenario (positive test): [--hostname;positive;FQDN --keytab;positive;ValidKeytab]
    ipa_join_1017  #test_scenario (negative test): [--hostname;positive;FQDN --keytab;positive;ValidKeytab --bindpw;negative;InvalidPW]
    ipa_join_1018  #test_scenario (positive test): [--hostname;positive;FQDN --keytab;positive;ValidKeytab --bindpw;positive;ValidPW]
    ipa_join_1019  #test_scenario (negative test): [--hostname;positive;FQDN --server;negative;NoSuchDomain]
    ipa_join_1020  #test_scenario (negative test): [--hostname;positive;FQDN --server;negative;NoSuchDomain --bindpw;positive;ValidPW]
    ipa_join_1021  #test_scenario (negative test): [--hostname;positive;FQDN --server;negative;NoSuchDomain --keytab;positive;ValidKeytab]
    ipa_join_1022  #test_scenario (negative test): [--hostname;positive;FQDN --server;negative;NoSuchDomain --keytab;positive;ValidKeytab --bindpw;positive;ValidPW]
    ipa_join_1023  #test_scenario (positive test): [--hostname;positive;FQDN --server;positive;FQDN]
    ipa_join_1024  #test_scenario (negative test): [--hostname;positive;FQDN --server;positive;FQDN --bindpw;negative;InvalidPW]
    ipa_join_1025  #test_scenario (positive test): [--hostname;positive;FQDN --server;positive;FQDN --bindpw;positive;ValidPW]
    ipa_join_1028  #test_scenario (positive test): [--hostname;positive;FQDN --server;positive;FQDN --keytab;positive;ValidKeytab]
    ipa_join_1029  #test_scenario (negative test): [--hostname;positive;FQDN --server;positive;FQDN --keytab;positive;ValidKeytab --bindpw;negative;InvalidPW]
    ipa_join_1030  #test_scenario (positive test): [--hostname;positive;FQDN --server;positive;FQDN --keytab;positive;ValidKeytab --bindpw;positive;ValidPW]
    ipa_join_1033  #test_scenario (positive test): [--keytab;positive;ValidKeytab]
    ipa_join_1034  #test_scenario (negative test): [--keytab;positive;ValidKeytab --bindpw;negative;InvalidPW]
    ipa_join_1035  #test_scenario (positive test): [--keytab;positive;ValidKeytab --bindpw;positive;ValidPW]
    ipa_join_1036  #test_scenario (negative test): [--server;negative;NoSuchDomain]
    ipa_join_1037  #test_scenario (negative test): [--server;negative;NoSuchDomain --bindpw;positive;ValidPW]
    ipa_join_1038  #test_scenario (negative test): [--server;negative;NoSuchDomain--keytab;positive;ValidKeytab]
    ipa_join_1039  #test_scenario (positive test): [--server;positive;FQDN]
    ipa_join_1040  #test_scenario (negative test): [--server;positive;FQDN --bindpw;negative;InvalidPW]
    ipa_join_1041  #test_scenario (positive test): [--server;positive;FQDN --bindpw;positive;ValidPW]
    ipa_join_1043  #test_scenario (positive test): [--server;positive;FQDN --keytab;positive;ValidKeytab]
    ipa_join_1044  #test_scenario (negative test): [--bindpw;negative;InvalidPW]
    ipa_join_envcleanup
} #ipajoin

ipa_join_envsetup()
{
    rlPhaseStartSetup "ipa_join_envsetup"
        #environment setup starts here
        install_ipa_client
        #environment setup ends   here
    rlPhaseEnd
} #envsetup

ipa_join_envcleanup()
{
    rlPhaseStartCleanup "ipa_join_envcleanup"
        #environment cleanup starts here
        uninstall_ipa_client
        # remove the possible leftover: test keytab file
        if [ -f $testKeytabfile ];then
            rm $testKeytabfile
        fi
        delete_clientHostEntry_FromIPAServer
        #environment cleanup ends   here
    rlPhaseEnd
} #envcleanup

ipa_join_1001()
{
    rlPhaseStartTest "ipa_join_1001 [positive test] --unenroll"
        local testID="ipa_join_1001"
        rlRun "ipa-join -u" "0" "unenroll client with '-u' " 
    rlPhaseEnd
} #ipa_join_1001

ipa_join_1011()
{
    rlPhaseStartTest "ipa_join_1011 [positive test] --hostname;positive;FQDN"
        local testID="ipa_join_1011"
        local tmpout=$TmpDir/ipa_join_1011.$RANDOM.out
        KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        rlRun "ipa-join --hostname=$hostname_TestValue " 0 "test options:  [hostname]=[$hostname_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1011

ipa_join_1012()
{
    rlPhaseStartTest "ipa_join_1012 [negative test] --hostname;positive;FQDN --bindpw;negative;InvalidPW"
        local testID="ipa_join_1012"
        local tmpout=$TmpDir/ipa_join_1012.$RANDOM.out
        KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local bindpw_TestValue_Negative="WrongPassword" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "we have to un-join before test starts"
        #remove the client host record
        ssh root@$serverFQDN "ipa host-add $clientFQDN --password=$OTP"
        qaRun "ipa-join --hostname=$hostname_TestValue  --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [bindpw]=[$bindpw_TestValue_Negative]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1012

ipa_join_1013()
{
    rlPhaseStartTest "ipa_join_1013 [positive test] --hostname;positive;FQDN --bindpw;positive;ValidPW"
        local testID="ipa_join_1013"
        local tmpout=$TmpDir/ipa_join_1013.$RANDOM.out
        #KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        rlRun "ipa-join --hostname=$hostname_TestValue  --bindpw=$OTP" 0 "test options:  [hostname]=[$hostname_TestValue] [bindpw]=[$bindpw_TestValue]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1013

ipa_join_1016()
{
    rlPhaseStartTest "ipa_join_1016 [positive test] --hostname;positive;FQDN --keytab;positive;ValidKeytab"
        local testID="ipa_join_1016"
        local tmpout=$TmpDir/ipa_join_1016.$RANDOM.out
        KinitAsAdmin
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        rlRun "ipa-join --hostname=$hostname_TestValue  --keytab=$keytab_TestValue " 0 "test options:  [hostname]=[$hostname_TestValue] [keytab]=[$keytab_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1016

ipa_join_1017()
{
    rlPhaseStartTest "ipa_join_1017 [negative test] --hostname;positive;FQDN --keytab;positive;ValidKeytab --bindpw;negative;InvalidPW"
        local testID="ipa_join_1017"
        local tmpout=$TmpDir/ipa_join_1017.$RANDOM.out
        KinitAsAdmin

        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN\" --password=$OTP" 0 "add $clientFQDN and set OTP"
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local bindpw_TestValue_Negative="WrongPassword" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        qaRun "ipa-join --hostname=$hostname_TestValue  --keytab=$keytab_TestValue  --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [keytab]=[$keytab_TestValue] [bindpw]=[$bindpw_TestValue_Negative]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1017

ipa_join_1018()
{
    rlPhaseStartTest "ipa_join_1018 [positive test] --hostname;positive;FQDN --keytab;positive;ValidKeytab --bindpw;positive;ValidPW"
        local testID="ipa_join_1018"
        local tmpout=$TmpDir/ipa_join_1018.$RANDOM.out
        #KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        rlRun "ipa-join --hostname=$hostname_TestValue  --keytab=$keytab_TestValue  --bindpw=$bindpw_TestValue " 0 "test options:  [hostname]=[$hostname_TestValue] [keytab]=[$keytab_TestValue] [bindpw]=[$bindpw_TestValue]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1018

ipa_join_1019()
{
    rlPhaseStartTest "ipa_join_1019 [negative test] --hostname;positive;FQDN --server;negative;NoSuchDomain"
        local testID="ipa_join_1019"
        local tmpout=$TmpDir/ipa_join_1019.$RANDOM.out
        KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue_Negative="No.Such.IPA.Server.Domain.com" #server;negative;NoSuchDomain
        local expectedErrMsg="libcurl failed to execute the HTTP POST transaction"
        local expectedErrCode=17
        qaRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue_Negative]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1019

ipa_join_1020()
{
    rlPhaseStartTest "ipa_join_1020 [negative test] --hostname;positive;FQDN --server;negative;NoSuchDomain --bindpw;positive;ValidPW"
        local testID="ipa_join_1020"
        local tmpout=$TmpDir/ipa_join_1020.$RANDOM.out
        #KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue_Negative="No.Such.IPA.Server.Domain.com" #server;negative;NoSuchDomain
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        local expectedErrMsg="Unable to determine root DN of $server_TestValue_Negative"
        local expectedErrCode=14
        qaRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue_Negative  --bindpw=$bindpw_TestValue " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue_Negative] [bindpw]=[$bindpw_TestValue]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1020

ipa_join_1021()
{
    rlPhaseStartTest "ipa_join_1021 [negative test] --hostname;positive;FQDN --server;negative;NoSuchDomain --keytab;positive;ValidKeytab"
        local testID="ipa_join_1021"
        local tmpout=$TmpDir/ipa_join_1021.$RANDOM.out
        KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue_Negative="No.Such.IPA.Server.Domain.com" #server;negative;NoSuchDomain
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local expectedErrMsg="libcurl failed to execute the HTTP POST transaction"
        local expectedErrCode=17
        qaRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue_Negative  --keytab=$keytab_TestValue " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue_Negative] [keytab]=[$keytab_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1021

ipa_join_1022()
{
    rlPhaseStartTest "ipa_join_1022 [negative test] --hostname;positive;FQDN --server;negative;NoSuchDomain --keytab;positive;ValidKeytab --bindpw;positive;ValidPW"
        local testID="ipa_join_1022"
        local tmpout=$TmpDir/ipa_join_1022.$RANDOM.out
        KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue_Negative="No.Such.IPA.Server.Domain.com" #server;negative;NoSuchDomain
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        local expectedErrMsg="Unable to determine root DN of $server_TestValue_Negative"
        local expectedErrCode=14
        qaRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue_Negative  --keytab=$keytab_TestValue  --bindpw=$bindpw_TestValue " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue_Negative] [keytab]=[$keytab_TestValue] [bindpw]=[$bindpw_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1022

ipa_join_1023()
{
    rlPhaseStartTest "ipa_join_1023 [positive test] --hostname;positive;FQDN --server;positive;FQDN"
        local testID="ipa_join_1023"
        local tmpout=$TmpDir/ipa_join_1023.$RANDOM.out
        KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue " 0 "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1023

ipa_join_1024()
{
    rlPhaseStartTest "ipa_join_1024 [negative test] --hostname;positive;FQDN --server;positive;FQDN --bindpw;negative;InvalidPW"
        local testID="ipa_join_1024"
        local tmpout=$TmpDir/ipa_join_1024.$RANDOM.out
        #KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        local bindpw_TestValue_Negative="WrongPassword" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP \"" 0 "add $clientFQDN from ipa server"
        qaRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue  --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue] [bindpw]=[$bindpw_TestValue_Negative]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1024

ipa_join_1025()
{
    rlPhaseStartTest "ipa_join_1025 [positive test] --hostname;positive;FQDN --server;positive;FQDN --bindpw;positive;ValidPW"
        local testID="ipa_join_1025"
        local tmpout=$TmpDir/ipa_join_1025.$RANDOM.out
        #KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP \"" 0 "add $clientFQDN from ipa server"
        rlRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue  --bindpw=$bindpw_TestValue " 0 "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue] [bindpw]=[$bindpw_TestValue]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1025

ipa_join_1028()
{
    rlPhaseStartTest "ipa_join_1028 [positive test] --hostname;positive;FQDN --server;positive;FQDN --keytab;positive;ValidKeytab"
        local testID="ipa_join_1028"
        local tmpout=$TmpDir/ipa_join_1028.$RANDOM.out
        KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN \"" 0 "add $clientFQDN from ipa server"
        rlRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue  --keytab=$keytab_TestValue " 0 "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue] [keytab]=[$keytab_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1028

ipa_join_1029()
{
    rlPhaseStartTest "ipa_join_1029 [negative test] --hostname;positive;FQDN --server;positive;FQDN --keytab;positive;ValidKeytab --bindpw;negative;InvalidPW"
        local testID="ipa_join_1029"
        local tmpout=$TmpDir/ipa_join_1029.$RANDOM.out
        #KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local bindpw_TestValue_Negative="WrongPassword" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP \"" 0 "add $clientFQDN from ipa server"
        qaRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue  --keytab=$keytab_TestValue  --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue] [keytab]=[$keytab_TestValue] [bindpw]=[$bindpw_TestValue_Negative]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1029

ipa_join_1030()
{
    rlPhaseStartTest "ipa_join_1030 [positive test] --hostname;positive;FQDN --server;positive;FQDN --keytab;positive;ValidKeytab --bindpw;positive;ValidPW"
        local testID="ipa_join_1030"
        local tmpout=$TmpDir/ipa_join_1030.$RANDOM.out
        #KinitAsAdmin
        local hostname_TestValue="$clientFQDN" #hostname;positive;FQDN
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP \"" 0 "add $clientFQDN from ipa server"
        rlRun "ipa-join --hostname=$hostname_TestValue  --server=$server_TestValue  --keytab=$keytab_TestValue  --bindpw=$bindpw_TestValue " 0 "test options:  [hostname]=[$hostname_TestValue] [server]=[$server_TestValue] [keytab]=[$keytab_TestValue] [bindpw]=[$bindpw_TestValue]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1030

ipa_join_1033()
{
    rlPhaseStartTest "ipa_join_1033 [positive test] --keytab;positive;ValidKeytab"
        local testID="ipa_join_1033"
        local tmpout=$TmpDir/ipa_join_1033.$RANDOM.out
        KinitAsAdmin
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN \"" 0 "add $clientFQDN from ipa server"
        rlRun "ipa-join --keytab=$keytab_TestValue " 0 "test options:  [keytab]=[$keytab_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1033

ipa_join_1034()
{
    rlPhaseStartTest "ipa_join_1034 [negative test] --keytab;positive;ValidKeytab --bindpw;negative;InvalidPW"
        local testID="ipa_join_1034"
        local tmpout=$TmpDir/ipa_join_1034.$RANDOM.out
        #KinitAsAdmin
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local bindpw_TestValue_Negative="WrongPassword" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP \"" 0 "add $clientFQDN from ipa server"
        qaRun "ipa-join --keytab=$keytab_TestValue  --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [keytab]=[$keytab_TestValue] [bindpw]=[$bindpw_TestValue_Negative]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1034

ipa_join_1035()
{
    rlPhaseStartTest "ipa_join_1035 [positive test] --keytab;positive;ValidKeytab --bindpw;positive;ValidPW"
        local testID="ipa_join_1035"
        local tmpout=$TmpDir/ipa_join_1035.$RANDOM.out
        #KinitAsAdmin
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP \"" 0 "add $clientFQDN from ipa server"
        rlRun "ipa-join --keytab=$keytab_TestValue  --bindpw=$bindpw_TestValue " 0 "test options:  [keytab]=[$keytab_TestValue] [bindpw]=[$bindpw_TestValue]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1035

ipa_join_1036()
{
    rlPhaseStartTest "ipa_join_1036 [negative test] --server;negative;NoSuchDomain"
        local testID="ipa_join_1036"
        local tmpout=$TmpDir/ipa_join_1036.$RANDOM.out
        KinitAsAdmin
        local server_TestValue_Negative="No.Such.IPA.Server.Domain.com" #server;negative;NoSuchDomain
        local expectedErrMsg="libcurl failed to execute the HTTP POST transaction"
        local expectedErrCode=17
        qaRun "ipa-join --server=$server_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [server]=[$server_TestValue_Negative]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1036

ipa_join_1037()
{
    rlPhaseStartTest "ipa_join_1037 [negative test] --server;negative;NoSuchDomain --bindpw;positive;ValidPW"
        local testID="ipa_join_1037"
        local tmpout=$TmpDir/ipa_join_1037.$RANDOM.out
        #KinitAsAdmin
        local server_TestValue_Negative="No.Such.IPA.Server.Domain.com" #server;negative;NoSuchDomain
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        local expectedErrMsg="Unable to determine root DN of $server_TestValue_Negative"
        local expectedErrCode=14
        qaRun "ipa-join --server=$server_TestValue_Negative  --bindpw=$bindpw_TestValue " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [server]=[$server_TestValue_Negative] [bindpw]=[$bindpw_TestValue]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1037

ipa_join_1038()
{
    rlPhaseStartTest "ipa_join_1038 [negative test] --server;negative;NoSuchDomain--keytab;positive;ValidKeytab"
        local testID="ipa_join_1038"
        local tmpout=$TmpDir/ipa_join_1038.$RANDOM.out
        KinitAsAdmin
        local server_TestValue_Negative="No.Such.IPA.Server.Domain.com" #server;negative;NoSuchDomain
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        local expectedErrMsg="libcurl failed to execute the HTTP POST transaction"
        local expectedErrCode=17
        qaRun "ipa-join --server=$server_TestValue_Negative  --keytab=$keytab_TestValue " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [server]=[$server_TestValue_Negative] [keytab]=[$keytab_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1038

ipa_join_1039()
{
    rlPhaseStartTest "ipa_join_1039 [positive test] --server;positive;FQDN"
        local testID="ipa_join_1039"
        local tmpout=$TmpDir/ipa_join_1039.$RANDOM.out
        KinitAsAdmin
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN \"" 0 "add $clientFQDN from ipa server"
        rlRun "ipa-join --server=$server_TestValue " 0 "test options:  [server]=[$server_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1039

ipa_join_1040()
{
    rlPhaseStartTest "ipa_join_1040 [negative test] --server;positive;FQDN --bindpw;negative;InvalidPW"
        local testID="ipa_join_1040"
        local tmpout=$TmpDir/ipa_join_1040.$RANDOM.out
        #KinitAsAdmin
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        local bindpw_TestValue_Negative="WrongPassword" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP\"" 0 "add $clientFQDN from ipa server"
        qaRun "ipa-join --server=$server_TestValue  --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [server]=[$server_TestValue] [bindpw]=[$bindpw_TestValue_Negative]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1040

ipa_join_1041()
{
    rlPhaseStartTest "ipa_join_1041 [positive test] --server;positive;FQDN --bindpw;positive;ValidPW"
        local testID="ipa_join_1041"
        local tmpout=$TmpDir/ipa_join_1041.$RANDOM.out
        #KinitAsAdmin
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        local bindpw_TestValue=$OTP #bindpw;positive;ValidPW
        rlRun "ipa-join --server=$server_TestValue  --bindpw=$bindpw_TestValue " 0 "test options:  [server]=[$server_TestValue] [bindpw]=[$bindpw_TestValue]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1041

ipa_join_1043()
{
    rlPhaseStartTest "ipa_join_1043 [positive test] --server;positive;FQDN --keytab;positive;ValidKeytab"
        local testID="ipa_join_1043"
        local tmpout=$TmpDir/ipa_join_1043.$RANDOM.out
        KinitAsAdmin
        local server_TestValue="$serverFQDN" #server;positive;FQDN
        local keytab_TestValue="$testKeytabfile" #keytab;positive;ValidKeytab
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN \"" 0 "add $clientFQDN from ipa server"
        rlRun "ipa-join --server=$server_TestValue  --keytab=$keytab_TestValue " 0 "test options:  [server]=[$server_TestValue] [keytab]=[$keytab_TestValue]" 
        Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1043

ipa_join_1044()
{
    rlPhaseStartTest "ipa_join_1044 [negative test] --bindpw;negative;InvalidPW"
        local tmpout=$TmpDir/ipa_join_1044.$RANDOM.out
        #KinitAsAdmin
        local bindpw_TestValue_Negative="WrongPassword" #bindpw;negative;InvalidPW
        local expectedErrMsg="Incorrect password"
        local expectedErrCode=15
        rlRun "ssh root@$serverFQDN \"ipa host-del $clientFQDN\"" 0 "delete $clientFQDN from ipa server"
        rlRun "ssh root@$serverFQDN \"ipa host-add $clientFQDN --password=$OTP \"" 0 "add $clientFQDN from ipa server"
        qaRun "ipa-join --bindpw=$bindpw_TestValue_Negative " "$tmpout" $expectedErrCode "$expectedErrMsg" "test options:  [bindpw]=[$bindpw_TestValue_Negative]" 
        #Kcleanup
        rm $tmpout
    rlPhaseEnd
} #ipa_join_1044

#END OF TEST CASE for [ipa-join]
